// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: background_ddls.sql

package querier

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const cancelPendingBackgroundDdlProgresses = `-- name: CancelPendingBackgroundDdlProgresses :exec
UPDATE background_ddl_progresses
SET cancelled_at = COALESCE(cancelled_at, NOW()),
    updated_at = NOW()
WHERE job_id = $1
  AND started_at IS NULL
  AND finished_at IS NULL
  AND failed_at IS NULL
  AND cancelled_at IS NULL
`

func (q *Queries) CancelPendingBackgroundDdlProgresses(ctx context.Context, jobID uuid.UUID) error {
	_, err := q.db.Exec(ctx, cancelPendingBackgroundDdlProgresses, jobID)
	return err
}

const createBackgroundDdlJob = `-- name: CreateBackgroundDdlJob :one
INSERT INTO background_ddl_jobs (
    id,
    cluster_uuid,
    database_name,
    statement
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, cluster_uuid, database_name, statement, task_id, created_at, started_at, cancel_requested_at, cancelled_at, finished_at, failed_at, failure_reason
`

type CreateBackgroundDdlJobParams struct {
	ID           uuid.UUID
	ClusterUuid  uuid.UUID
	DatabaseName string
	Statement    string
}

func (q *Queries) CreateBackgroundDdlJob(ctx context.Context, arg CreateBackgroundDdlJobParams) (*BackgroundDdlJob, error) {
	row := q.db.QueryRow(ctx, createBackgroundDdlJob,
		arg.ID,
		arg.ClusterUuid,
		arg.DatabaseName,
		arg.Statement,
	)
	var i BackgroundDdlJob
	err := row.Scan(
		&i.ID,
		&i.ClusterUuid,
		&i.DatabaseName,
		&i.Statement,
		&i.TaskID,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CancelRequestedAt,
		&i.CancelledAt,
		&i.FinishedAt,
		&i.FailedAt,
		&i.FailureReason,
	)
	return &i, err
}

const createBackgroundDdlProgress = `-- name: CreateBackgroundDdlProgress :exec
INSERT INTO background_ddl_progresses (
    id,
    job_id,
    seq,
    statement,
    statement_kind,
    target_kind,
    target_type,
    target_schema,
    target_name,
    target_identity,
    expect_relation_exists
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
`

type CreateBackgroundDdlProgressParams struct {
	ID                   uuid.UUID
	JobID                uuid.UUID
	Seq                  int32
	Statement            string
	StatementKind        string
	TargetKind           string
	TargetType           *string
	TargetSchema         *string
	TargetName           *string
	TargetIdentity       *string
	ExpectRelationExists *bool
}

func (q *Queries) CreateBackgroundDdlProgress(ctx context.Context, arg CreateBackgroundDdlProgressParams) error {
	_, err := q.db.Exec(ctx, createBackgroundDdlProgress,
		arg.ID,
		arg.JobID,
		arg.Seq,
		arg.Statement,
		arg.StatementKind,
		arg.TargetKind,
		arg.TargetType,
		arg.TargetSchema,
		arg.TargetName,
		arg.TargetIdentity,
		arg.ExpectRelationExists,
	)
	return err
}

const getBackgroundDdlJob = `-- name: GetBackgroundDdlJob :one
SELECT id, cluster_uuid, database_name, statement, task_id, created_at, started_at, cancel_requested_at, cancelled_at, finished_at, failed_at, failure_reason
FROM background_ddl_jobs
WHERE id = $1
`

func (q *Queries) GetBackgroundDdlJob(ctx context.Context, id uuid.UUID) (*BackgroundDdlJob, error) {
	row := q.db.QueryRow(ctx, getBackgroundDdlJob, id)
	var i BackgroundDdlJob
	err := row.Scan(
		&i.ID,
		&i.ClusterUuid,
		&i.DatabaseName,
		&i.Statement,
		&i.TaskID,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CancelRequestedAt,
		&i.CancelledAt,
		&i.FinishedAt,
		&i.FailedAt,
		&i.FailureReason,
	)
	return &i, err
}

const getNextBackgroundDdlProgress = `-- name: GetNextBackgroundDdlProgress :one
SELECT id, job_id, seq, statement, statement_kind, target_kind, target_type, target_schema, target_name, target_identity, expect_relation_exists, rw_job_ids, dispatched_at, started_at, last_progress, last_progress_tracked_at, estimated_finished_at, finished_at, cancelled_at, failed_at, failure_reason, created_at, updated_at
FROM background_ddl_progresses
WHERE job_id = $1
  AND finished_at IS NULL
  AND failed_at IS NULL
  AND cancelled_at IS NULL
ORDER BY seq ASC
LIMIT 1
`

func (q *Queries) GetNextBackgroundDdlProgress(ctx context.Context, jobID uuid.UUID) (*BackgroundDdlProgress, error) {
	row := q.db.QueryRow(ctx, getNextBackgroundDdlProgress, jobID)
	var i BackgroundDdlProgress
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Seq,
		&i.Statement,
		&i.StatementKind,
		&i.TargetKind,
		&i.TargetType,
		&i.TargetSchema,
		&i.TargetName,
		&i.TargetIdentity,
		&i.ExpectRelationExists,
		&i.RwJobIds,
		&i.DispatchedAt,
		&i.StartedAt,
		&i.LastProgress,
		&i.LastProgressTrackedAt,
		&i.EstimatedFinishedAt,
		&i.FinishedAt,
		&i.CancelledAt,
		&i.FailedAt,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listBackgroundDdlJobs = `-- name: ListBackgroundDdlJobs :many
SELECT id, cluster_uuid, database_name, statement, task_id, created_at, started_at, cancel_requested_at, cancelled_at, finished_at, failed_at, failure_reason
FROM background_ddl_jobs
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListBackgroundDdlJobs(ctx context.Context) ([]*BackgroundDdlJob, error) {
	rows, err := q.db.Query(ctx, listBackgroundDdlJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*BackgroundDdlJob
	for rows.Next() {
		var i BackgroundDdlJob
		if err := rows.Scan(
			&i.ID,
			&i.ClusterUuid,
			&i.DatabaseName,
			&i.Statement,
			&i.TaskID,
			&i.CreatedAt,
			&i.StartedAt,
			&i.CancelRequestedAt,
			&i.CancelledAt,
			&i.FinishedAt,
			&i.FailedAt,
			&i.FailureReason,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBackgroundDdlProgresses = `-- name: ListBackgroundDdlProgresses :many
SELECT id, job_id, seq, statement, statement_kind, target_kind, target_type, target_schema, target_name, target_identity, expect_relation_exists, rw_job_ids, dispatched_at, started_at, last_progress, last_progress_tracked_at, estimated_finished_at, finished_at, cancelled_at, failed_at, failure_reason, created_at, updated_at
FROM background_ddl_progresses
ORDER BY job_id ASC, seq ASC
`

func (q *Queries) ListBackgroundDdlProgresses(ctx context.Context) ([]*BackgroundDdlProgress, error) {
	rows, err := q.db.Query(ctx, listBackgroundDdlProgresses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*BackgroundDdlProgress
	for rows.Next() {
		var i BackgroundDdlProgress
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.Seq,
			&i.Statement,
			&i.StatementKind,
			&i.TargetKind,
			&i.TargetType,
			&i.TargetSchema,
			&i.TargetName,
			&i.TargetIdentity,
			&i.ExpectRelationExists,
			&i.RwJobIds,
			&i.DispatchedAt,
			&i.StartedAt,
			&i.LastProgress,
			&i.LastProgressTrackedAt,
			&i.EstimatedFinishedAt,
			&i.FinishedAt,
			&i.CancelledAt,
			&i.FailedAt,
			&i.FailureReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBackgroundDdlProgressesByJob = `-- name: ListBackgroundDdlProgressesByJob :many
SELECT id, job_id, seq, statement, statement_kind, target_kind, target_type, target_schema, target_name, target_identity, expect_relation_exists, rw_job_ids, dispatched_at, started_at, last_progress, last_progress_tracked_at, estimated_finished_at, finished_at, cancelled_at, failed_at, failure_reason, created_at, updated_at
FROM background_ddl_progresses
WHERE job_id = $1
ORDER BY seq ASC
`

func (q *Queries) ListBackgroundDdlProgressesByJob(ctx context.Context, jobID uuid.UUID) ([]*BackgroundDdlProgress, error) {
	rows, err := q.db.Query(ctx, listBackgroundDdlProgressesByJob, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*BackgroundDdlProgress
	for rows.Next() {
		var i BackgroundDdlProgress
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.Seq,
			&i.Statement,
			&i.StatementKind,
			&i.TargetKind,
			&i.TargetType,
			&i.TargetSchema,
			&i.TargetName,
			&i.TargetIdentity,
			&i.ExpectRelationExists,
			&i.RwJobIds,
			&i.DispatchedAt,
			&i.StartedAt,
			&i.LastProgress,
			&i.LastProgressTrackedAt,
			&i.EstimatedFinishedAt,
			&i.FinishedAt,
			&i.CancelledAt,
			&i.FailedAt,
			&i.FailureReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markBackgroundDdlJobCancelRequested = `-- name: MarkBackgroundDdlJobCancelRequested :exec
UPDATE background_ddl_jobs
SET cancel_requested_at = COALESCE(cancel_requested_at, NOW())
WHERE id = $1
`

func (q *Queries) MarkBackgroundDdlJobCancelRequested(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markBackgroundDdlJobCancelRequested, id)
	return err
}

const markBackgroundDdlJobCancelled = `-- name: MarkBackgroundDdlJobCancelled :exec
UPDATE background_ddl_jobs
SET cancelled_at = COALESCE(cancelled_at, NOW())
WHERE id = $1
`

func (q *Queries) MarkBackgroundDdlJobCancelled(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markBackgroundDdlJobCancelled, id)
	return err
}

const markBackgroundDdlJobFailed = `-- name: MarkBackgroundDdlJobFailed :exec
UPDATE background_ddl_jobs
SET failed_at = COALESCE(failed_at, NOW()),
    failure_reason = $2
WHERE id = $1
`

type MarkBackgroundDdlJobFailedParams struct {
	ID            uuid.UUID
	FailureReason *string
}

func (q *Queries) MarkBackgroundDdlJobFailed(ctx context.Context, arg MarkBackgroundDdlJobFailedParams) error {
	_, err := q.db.Exec(ctx, markBackgroundDdlJobFailed, arg.ID, arg.FailureReason)
	return err
}

const markBackgroundDdlJobFinished = `-- name: MarkBackgroundDdlJobFinished :exec
UPDATE background_ddl_jobs
SET finished_at = COALESCE(finished_at, NOW())
WHERE id = $1
`

func (q *Queries) MarkBackgroundDdlJobFinished(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markBackgroundDdlJobFinished, id)
	return err
}

const markBackgroundDdlJobStarted = `-- name: MarkBackgroundDdlJobStarted :exec
UPDATE background_ddl_jobs
SET started_at = COALESCE(started_at, NOW())
WHERE id = $1
`

func (q *Queries) MarkBackgroundDdlJobStarted(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markBackgroundDdlJobStarted, id)
	return err
}

const markBackgroundDdlProgressCancelled = `-- name: MarkBackgroundDdlProgressCancelled :exec
UPDATE background_ddl_progresses
SET cancelled_at = COALESCE(cancelled_at, NOW()),
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkBackgroundDdlProgressCancelled(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markBackgroundDdlProgressCancelled, id)
	return err
}

const markBackgroundDdlProgressFailed = `-- name: MarkBackgroundDdlProgressFailed :exec
UPDATE background_ddl_progresses
SET failed_at = COALESCE(failed_at, NOW()),
    failure_reason = $2,
    updated_at = NOW()
WHERE id = $1
`

type MarkBackgroundDdlProgressFailedParams struct {
	ID            uuid.UUID
	FailureReason *string
}

func (q *Queries) MarkBackgroundDdlProgressFailed(ctx context.Context, arg MarkBackgroundDdlProgressFailedParams) error {
	_, err := q.db.Exec(ctx, markBackgroundDdlProgressFailed, arg.ID, arg.FailureReason)
	return err
}

const markBackgroundDdlProgressFinished = `-- name: MarkBackgroundDdlProgressFinished :exec
UPDATE background_ddl_progresses
SET finished_at = COALESCE(finished_at, NOW()),
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkBackgroundDdlProgressFinished(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markBackgroundDdlProgressFinished, id)
	return err
}

const markBackgroundDdlProgressStarted = `-- name: MarkBackgroundDdlProgressStarted :exec
UPDATE background_ddl_progresses
SET dispatched_at = COALESCE(dispatched_at, NOW()),
    started_at = COALESCE(started_at, NOW()),
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkBackgroundDdlProgressStarted(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markBackgroundDdlProgressStarted, id)
	return err
}

const updateBackgroundDdlJobTaskID = `-- name: UpdateBackgroundDdlJobTaskID :exec
UPDATE background_ddl_jobs
SET task_id = $2
WHERE id = $1
`

type UpdateBackgroundDdlJobTaskIDParams struct {
	ID     uuid.UUID
	TaskID *int32
}

func (q *Queries) UpdateBackgroundDdlJobTaskID(ctx context.Context, arg UpdateBackgroundDdlJobTaskIDParams) error {
	_, err := q.db.Exec(ctx, updateBackgroundDdlJobTaskID, arg.ID, arg.TaskID)
	return err
}

const updateBackgroundDdlProgressTracking = `-- name: UpdateBackgroundDdlProgressTracking :exec
UPDATE background_ddl_progresses
SET rw_job_ids = $2,
    last_progress = $3,
    last_progress_tracked_at = $4,
    estimated_finished_at = $5,
    updated_at = NOW()
WHERE id = $1
`

type UpdateBackgroundDdlProgressTrackingParams struct {
	ID                    uuid.UUID
	RwJobIds              []int64
	LastProgress          *float64
	LastProgressTrackedAt *time.Time
	EstimatedFinishedAt   *time.Time
}

func (q *Queries) UpdateBackgroundDdlProgressTracking(ctx context.Context, arg UpdateBackgroundDdlProgressTrackingParams) error {
	_, err := q.db.Exec(ctx, updateBackgroundDdlProgressTracking,
		arg.ID,
		arg.RwJobIds,
		arg.LastProgress,
		arg.LastProgressTrackedAt,
		arg.EstimatedFinishedAt,
	)
	return err
}
