// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: clusters.sql

package querier

import (
	"context"

	"github.com/google/uuid"
)

const createCluster = `-- name: CreateCluster :one
INSERT INTO clusters (
    cluster_name,
    sql_connection_string,
    meta_node_grpc_url,
    meta_node_http_url
) VALUES (
    $1, $2, $3, $4
)
RETURNING cluster_uuid, cluster_name, sql_connection_string, meta_node_grpc_url, meta_node_http_url, created_at, updated_at
`

type CreateClusterParams struct {
	ClusterName         string
	SqlConnectionString string
	MetaNodeGrpcUrl     string
	MetaNodeHttpUrl     string
}

func (q *Queries) CreateCluster(ctx context.Context, arg CreateClusterParams) (*Cluster, error) {
	row := q.db.QueryRow(ctx, createCluster,
		arg.ClusterName,
		arg.SqlConnectionString,
		arg.MetaNodeGrpcUrl,
		arg.MetaNodeHttpUrl,
	)
	var i Cluster
	err := row.Scan(
		&i.ClusterUuid,
		&i.ClusterName,
		&i.SqlConnectionString,
		&i.MetaNodeGrpcUrl,
		&i.MetaNodeHttpUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deleteCluster = `-- name: DeleteCluster :exec
DELETE FROM clusters
WHERE cluster_uuid = $1
`

func (q *Queries) DeleteCluster(ctx context.Context, clusterUuid uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCluster, clusterUuid)
	return err
}

const getCluster = `-- name: GetCluster :one
SELECT cluster_uuid, cluster_name, sql_connection_string, meta_node_grpc_url, meta_node_http_url, created_at, updated_at
FROM clusters
WHERE cluster_uuid = $1
`

func (q *Queries) GetCluster(ctx context.Context, clusterUuid uuid.UUID) (*Cluster, error) {
	row := q.db.QueryRow(ctx, getCluster, clusterUuid)
	var i Cluster
	err := row.Scan(
		&i.ClusterUuid,
		&i.ClusterName,
		&i.SqlConnectionString,
		&i.MetaNodeGrpcUrl,
		&i.MetaNodeHttpUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listClusters = `-- name: ListClusters :many
SELECT cluster_uuid, cluster_name, sql_connection_string, meta_node_grpc_url, meta_node_http_url, created_at, updated_at
FROM clusters
ORDER BY created_at DESC, cluster_name ASC
`

func (q *Queries) ListClusters(ctx context.Context) ([]*Cluster, error) {
	rows, err := q.db.Query(ctx, listClusters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Cluster
	for rows.Next() {
		var i Cluster
		if err := rows.Scan(
			&i.ClusterUuid,
			&i.ClusterName,
			&i.SqlConnectionString,
			&i.MetaNodeGrpcUrl,
			&i.MetaNodeHttpUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCluster = `-- name: UpdateCluster :one
UPDATE clusters
SET cluster_name = $2,
    sql_connection_string = $3,
    meta_node_grpc_url = $4,
    meta_node_http_url = $5,
    updated_at = NOW()
WHERE cluster_uuid = $1
RETURNING cluster_uuid, cluster_name, sql_connection_string, meta_node_grpc_url, meta_node_http_url, created_at, updated_at
`

type UpdateClusterParams struct {
	ClusterUuid         uuid.UUID
	ClusterName         string
	SqlConnectionString string
	MetaNodeGrpcUrl     string
	MetaNodeHttpUrl     string
}

func (q *Queries) UpdateCluster(ctx context.Context, arg UpdateClusterParams) (*Cluster, error) {
	row := q.db.QueryRow(ctx, updateCluster,
		arg.ClusterUuid,
		arg.ClusterName,
		arg.SqlConnectionString,
		arg.MetaNodeGrpcUrl,
		arg.MetaNodeHttpUrl,
	)
	var i Cluster
	err := row.Scan(
		&i.ClusterUuid,
		&i.ClusterName,
		&i.SqlConnectionString,
		&i.MetaNodeGrpcUrl,
		&i.MetaNodeHttpUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
