// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: counter.sql

package querier

import (
	"context"
)

const getCounter = `-- name: GetCounter :one
SELECT id, value FROM counter WHERE id = 1
`

func (q *Queries) GetCounter(ctx context.Context) (*Counter, error) {
	row := q.db.QueryRow(ctx, getCounter)
	var i Counter
	err := row.Scan(&i.ID, &i.Value)
	return &i, err
}

const incrementCounter = `-- name: IncrementCounter :exec
UPDATE counter SET value = value + 1 WHERE id = 1
`

func (q *Queries) IncrementCounter(ctx context.Context) error {
	_, err := q.db.Exec(ctx, incrementCounter)
	return err
}
