// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package querier

import (
	"time"

	"github.com/google/uuid"
)

type BackgroundDdlJob struct {
	ID                uuid.UUID
	ClusterUuid       uuid.UUID
	DatabaseName      string
	Statement         string
	TaskID            *int32
	CreatedAt         time.Time
	StartedAt         *time.Time
	CancelRequestedAt *time.Time
	CancelledAt       *time.Time
	FinishedAt        *time.Time
	FailedAt          *time.Time
	FailureReason     *string
}

type BackgroundDdlProgress struct {
	ID                    uuid.UUID
	JobID                 uuid.UUID
	Seq                   int32
	Statement             string
	StatementKind         string
	TargetKind            string
	TargetType            *string
	TargetSchema          *string
	TargetName            *string
	TargetIdentity        *string
	ExpectRelationExists  *bool
	RwJobIds              []int64
	DispatchedAt          *time.Time
	StartedAt             *time.Time
	LastProgress          *float64
	LastProgressTrackedAt *time.Time
	EstimatedFinishedAt   *time.Time
	FinishedAt            *time.Time
	CancelledAt           *time.Time
	FailedAt              *time.Time
	FailureReason         *string
	CreatedAt             time.Time
	UpdatedAt             time.Time
}

type Cluster struct {
	ClusterUuid         uuid.UUID
	ClusterName         string
	SqlConnectionString string
	MetaNodeGrpcUrl     string
	MetaNodeHttpUrl     string
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

type Counter struct {
	ID    int32
	Value int32
}

type Notebook struct {
	NotebookUuid uuid.UUID
	NotebookName string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type NotebookCell struct {
	CellUuid      uuid.UUID
	NotebookUuid  uuid.UUID
	CellType      string
	ClusterUuid   uuid.NullUUID
	DatabaseName  *string
	Content       string
	OrderIndex    int32
	CreatedAt     time.Time
	UpdatedAt     time.Time
	BackgroundDdl bool
}
