// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package querier

import (
	"time"

	"github.com/google/uuid"
)

type Cluster struct {
	ClusterUuid         uuid.UUID
	ClusterName         string
	SqlConnectionString string
	MetaNodeGrpcUrl     string
	MetaNodeHttpUrl     string
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

type Counter struct {
	ID    int32
	Value int32
}

type Notebook struct {
	NotebookUuid uuid.UUID
	NotebookName string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type NotebookCell struct {
	CellUuid      uuid.UUID
	NotebookUuid  uuid.UUID
	CellType      string
	ClusterUuid   uuid.NullUUID
	DatabaseName  *string
	Content       string
	OrderIndex    int32
	CreatedAt     time.Time
	UpdatedAt     time.Time
	BackgroundDdl bool
}
