// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notebooks.sql

package querier

import (
	"context"

	"github.com/google/uuid"
)

const createNotebook = `-- name: CreateNotebook :one
INSERT INTO notebooks (
    notebook_name
) VALUES (
    $1
)
RETURNING notebook_uuid, notebook_name, created_at, updated_at
`

func (q *Queries) CreateNotebook(ctx context.Context, notebookName string) (*Notebook, error) {
	row := q.db.QueryRow(ctx, createNotebook, notebookName)
	var i Notebook
	err := row.Scan(
		&i.NotebookUuid,
		&i.NotebookName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const createNotebookCell = `-- name: CreateNotebookCell :one
INSERT INTO notebook_cells (
    notebook_uuid,
    cell_type,
    cluster_uuid,
    database_name,
    background_ddl,
    content,
    order_index
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING cell_uuid, notebook_uuid, cell_type, cluster_uuid, database_name, content, order_index, created_at, updated_at, background_ddl
`

type CreateNotebookCellParams struct {
	NotebookUuid  uuid.UUID
	CellType      string
	ClusterUuid   uuid.NullUUID
	DatabaseName  *string
	BackgroundDdl bool
	Content       string
	OrderIndex    int32
}

func (q *Queries) CreateNotebookCell(ctx context.Context, arg CreateNotebookCellParams) (*NotebookCell, error) {
	row := q.db.QueryRow(ctx, createNotebookCell,
		arg.NotebookUuid,
		arg.CellType,
		arg.ClusterUuid,
		arg.DatabaseName,
		arg.BackgroundDdl,
		arg.Content,
		arg.OrderIndex,
	)
	var i NotebookCell
	err := row.Scan(
		&i.CellUuid,
		&i.NotebookUuid,
		&i.CellType,
		&i.ClusterUuid,
		&i.DatabaseName,
		&i.Content,
		&i.OrderIndex,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BackgroundDdl,
	)
	return &i, err
}

const deleteNotebook = `-- name: DeleteNotebook :exec
DELETE FROM notebooks
WHERE notebook_uuid = $1
`

func (q *Queries) DeleteNotebook(ctx context.Context, notebookUuid uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteNotebook, notebookUuid)
	return err
}

const deleteNotebookCell = `-- name: DeleteNotebookCell :exec
DELETE FROM notebook_cells
WHERE notebook_uuid = $1 AND cell_uuid = $2
`

type DeleteNotebookCellParams struct {
	NotebookUuid uuid.UUID
	CellUuid     uuid.UUID
}

func (q *Queries) DeleteNotebookCell(ctx context.Context, arg DeleteNotebookCellParams) error {
	_, err := q.db.Exec(ctx, deleteNotebookCell, arg.NotebookUuid, arg.CellUuid)
	return err
}

const getNextNotebookCellOrder = `-- name: GetNextNotebookCellOrder :one
SELECT COALESCE(MAX(order_index) + 1, 0)::INTEGER AS next_order
FROM notebook_cells
WHERE notebook_uuid = $1
`

func (q *Queries) GetNextNotebookCellOrder(ctx context.Context, notebookUuid uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getNextNotebookCellOrder, notebookUuid)
	var next_order int32
	err := row.Scan(&next_order)
	return next_order, err
}

const getNotebook = `-- name: GetNotebook :one
SELECT notebook_uuid, notebook_name, created_at, updated_at
FROM notebooks
WHERE notebook_uuid = $1
`

func (q *Queries) GetNotebook(ctx context.Context, notebookUuid uuid.UUID) (*Notebook, error) {
	row := q.db.QueryRow(ctx, getNotebook, notebookUuid)
	var i Notebook
	err := row.Scan(
		&i.NotebookUuid,
		&i.NotebookName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getNotebookCell = `-- name: GetNotebookCell :one
SELECT cell_uuid, notebook_uuid, cell_type, cluster_uuid, database_name, content, order_index, created_at, updated_at, background_ddl
FROM notebook_cells
WHERE notebook_uuid = $1 AND cell_uuid = $2
`

type GetNotebookCellParams struct {
	NotebookUuid uuid.UUID
	CellUuid     uuid.UUID
}

func (q *Queries) GetNotebookCell(ctx context.Context, arg GetNotebookCellParams) (*NotebookCell, error) {
	row := q.db.QueryRow(ctx, getNotebookCell, arg.NotebookUuid, arg.CellUuid)
	var i NotebookCell
	err := row.Scan(
		&i.CellUuid,
		&i.NotebookUuid,
		&i.CellType,
		&i.ClusterUuid,
		&i.DatabaseName,
		&i.Content,
		&i.OrderIndex,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BackgroundDdl,
	)
	return &i, err
}

const listNotebookCells = `-- name: ListNotebookCells :many
SELECT cell_uuid, notebook_uuid, cell_type, cluster_uuid, database_name, content, order_index, created_at, updated_at, background_ddl
FROM notebook_cells
WHERE notebook_uuid = $1
ORDER BY order_index ASC, created_at ASC
`

func (q *Queries) ListNotebookCells(ctx context.Context, notebookUuid uuid.UUID) ([]*NotebookCell, error) {
	rows, err := q.db.Query(ctx, listNotebookCells, notebookUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*NotebookCell
	for rows.Next() {
		var i NotebookCell
		if err := rows.Scan(
			&i.CellUuid,
			&i.NotebookUuid,
			&i.CellType,
			&i.ClusterUuid,
			&i.DatabaseName,
			&i.Content,
			&i.OrderIndex,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BackgroundDdl,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotebooks = `-- name: ListNotebooks :many
SELECT notebook_uuid, notebook_name, created_at, updated_at
FROM notebooks
ORDER BY updated_at DESC, created_at DESC
`

func (q *Queries) ListNotebooks(ctx context.Context) ([]*Notebook, error) {
	rows, err := q.db.Query(ctx, listNotebooks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Notebook
	for rows.Next() {
		var i Notebook
		if err := rows.Scan(
			&i.NotebookUuid,
			&i.NotebookName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNotebookCell = `-- name: UpdateNotebookCell :one
UPDATE notebook_cells
SET cell_type = $3,
    cluster_uuid = $4,
    database_name = $5,
    background_ddl = $6,
    content = $7,
    updated_at = NOW()
WHERE notebook_uuid = $1 AND cell_uuid = $2
RETURNING cell_uuid, notebook_uuid, cell_type, cluster_uuid, database_name, content, order_index, created_at, updated_at, background_ddl
`

type UpdateNotebookCellParams struct {
	NotebookUuid  uuid.UUID
	CellUuid      uuid.UUID
	CellType      string
	ClusterUuid   uuid.NullUUID
	DatabaseName  *string
	BackgroundDdl bool
	Content       string
}

func (q *Queries) UpdateNotebookCell(ctx context.Context, arg UpdateNotebookCellParams) (*NotebookCell, error) {
	row := q.db.QueryRow(ctx, updateNotebookCell,
		arg.NotebookUuid,
		arg.CellUuid,
		arg.CellType,
		arg.ClusterUuid,
		arg.DatabaseName,
		arg.BackgroundDdl,
		arg.Content,
	)
	var i NotebookCell
	err := row.Scan(
		&i.CellUuid,
		&i.NotebookUuid,
		&i.CellType,
		&i.ClusterUuid,
		&i.DatabaseName,
		&i.Content,
		&i.OrderIndex,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BackgroundDdl,
	)
	return &i, err
}

const updateNotebookCellOrder = `-- name: UpdateNotebookCellOrder :exec
UPDATE notebook_cells
SET order_index = $3,
    updated_at = NOW()
WHERE notebook_uuid = $1 AND cell_uuid = $2
`

type UpdateNotebookCellOrderParams struct {
	NotebookUuid uuid.UUID
	CellUuid     uuid.UUID
	OrderIndex   int32
}

func (q *Queries) UpdateNotebookCellOrder(ctx context.Context, arg UpdateNotebookCellOrderParams) error {
	_, err := q.db.Exec(ctx, updateNotebookCellOrder, arg.NotebookUuid, arg.CellUuid, arg.OrderIndex)
	return err
}

const updateNotebookTimestamp = `-- name: UpdateNotebookTimestamp :exec
UPDATE notebooks
SET updated_at = NOW()
WHERE notebook_uuid = $1
`

func (q *Queries) UpdateNotebookTimestamp(ctx context.Context, notebookUuid uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateNotebookTimestamp, notebookUuid)
	return err
}
