// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package querier

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateCluster(ctx context.Context, arg CreateClusterParams) (*Cluster, error)
	CreateNotebook(ctx context.Context, notebookName string) (*Notebook, error)
	CreateNotebookCell(ctx context.Context, arg CreateNotebookCellParams) (*NotebookCell, error)
	DeleteCluster(ctx context.Context, clusterUuid uuid.UUID) error
	DeleteNotebook(ctx context.Context, notebookUuid uuid.UUID) error
	DeleteNotebookCell(ctx context.Context, arg DeleteNotebookCellParams) error
	GetCluster(ctx context.Context, clusterUuid uuid.UUID) (*Cluster, error)
	GetCounter(ctx context.Context) (*Counter, error)
	GetNextNotebookCellOrder(ctx context.Context, notebookUuid uuid.UUID) (int32, error)
	GetNotebook(ctx context.Context, notebookUuid uuid.UUID) (*Notebook, error)
	GetNotebookCell(ctx context.Context, arg GetNotebookCellParams) (*NotebookCell, error)
	IncrementCounter(ctx context.Context) error
	ListClusters(ctx context.Context) ([]*Cluster, error)
	ListNotebookCells(ctx context.Context, notebookUuid uuid.UUID) ([]*NotebookCell, error)
	ListNotebooks(ctx context.Context) ([]*Notebook, error)
	UpdateCluster(ctx context.Context, arg UpdateClusterParams) (*Cluster, error)
	UpdateNotebookCell(ctx context.Context, arg UpdateNotebookCellParams) (*NotebookCell, error)
	UpdateNotebookCellOrder(ctx context.Context, arg UpdateNotebookCellOrderParams) error
	UpdateNotebookTimestamp(ctx context.Context, notebookUuid uuid.UUID) error
}

var _ Querier = (*Queries)(nil)
