// Package apigen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/cloudcarver/anclax DO NOT EDIT.
package apigen

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"github.com/gofiber/fiber/v3"
	"github.com/google/uuid"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"
)

// Defines values for BackgroundDdlStatementKind.
const (
	BackgroundDdlStatementKindSET        BackgroundDdlStatementKind = "SET"
	BackgroundDdlStatementKindTRACKEDDDL BackgroundDdlStatementKind = "TRACKED_DDL"
	BackgroundDdlStatementKindDIRECT     BackgroundDdlStatementKind = "DIRECT"
)

// Defines values for BackgroundDdlStatus.
const (
	BackgroundDdlStatusPending         BackgroundDdlStatus = "pending"
	BackgroundDdlStatusRunning         BackgroundDdlStatus = "running"
	BackgroundDdlStatusCancelRequested BackgroundDdlStatus = "cancel_requested"
	BackgroundDdlStatusCancelled       BackgroundDdlStatus = "cancelled"
	BackgroundDdlStatusFinished        BackgroundDdlStatus = "finished"
	BackgroundDdlStatusFailed          BackgroundDdlStatus = "failed"
)

// Defines values for BackgroundDdlTargetKind.
const (
	BackgroundDdlTargetKindNone     BackgroundDdlTargetKind = "none"
	BackgroundDdlTargetKindRelation BackgroundDdlTargetKind = "relation"
	BackgroundDdlTargetKindFunction BackgroundDdlTargetKind = "function"
)

// Defines values for NotebookCellType.
const (
	NotebookCellTypeSQL   NotebookCellType = "SQL"
	NotebookCellTypeShell NotebookCellType = "Shell"
)

// BackgroundDdlJob defines model for BackgroundDdlJob.
type BackgroundDdlJob struct {
	CancelRequestedAt *time.Time              `json:"cancelRequestedAt,omitempty"`
	CancelledAt       *time.Time              `json:"cancelledAt,omitempty"`
	ClusterUuid       uuid.UUID               `json:"clusterUuid"`
	CreatedAt         time.Time               `json:"createdAt"`
	Database          string                  `json:"database"`
	FailedAt          *time.Time              `json:"failedAt,omitempty"`
	FailureReason     *string                 `json:"failureReason,omitempty"`
	FinishedAt        *time.Time              `json:"finishedAt,omitempty"`
	Id                uuid.UUID               `json:"id"`
	Progresses        []BackgroundDdlProgress `json:"progresses"`
	StartedAt         *time.Time              `json:"startedAt,omitempty"`
	Statement         string                  `json:"statement"`
	Status            BackgroundDdlStatus     `json:"status"`
}

// BackgroundDdlList defines model for BackgroundDdlList.
type BackgroundDdlList struct {
	Jobs []BackgroundDdlJob `json:"jobs"`
}

// BackgroundDdlProgress defines model for BackgroundDdlProgress.
type BackgroundDdlProgress struct {
	CancelledAt           *time.Time                 `json:"cancelledAt,omitempty"`
	EstimatedFinishedAt   *time.Time                 `json:"estimatedFinishedAt,omitempty"`
	FailedAt              *time.Time                 `json:"failedAt,omitempty"`
	FailureReason         *string                    `json:"failureReason,omitempty"`
	FinishedAt            *time.Time                 `json:"finishedAt,omitempty"`
	Id                    uuid.UUID                  `json:"id"`
	LastProgress          *float64                   `json:"lastProgress,omitempty"`
	LastProgressTrackedAt *time.Time                 `json:"lastProgressTrackedAt,omitempty"`
	RwJobIds              []int64                    `json:"rwJobIds"`
	Seq                   int32                      `json:"seq"`
	StartedAt             *time.Time                 `json:"startedAt,omitempty"`
	Statement             string                     `json:"statement"`
	StatementKind         BackgroundDdlStatementKind `json:"statementKind"`
	Status                BackgroundDdlStatus        `json:"status"`
	TargetIdentity        *string                    `json:"targetIdentity,omitempty"`
	TargetKind            BackgroundDdlTargetKind    `json:"targetKind"`
	TargetName            *string                    `json:"targetName,omitempty"`
	TargetSchema          *string                    `json:"targetSchema,omitempty"`
	TargetType            *string                    `json:"targetType,omitempty"`
}

// BackgroundProgressCluster defines model for BackgroundProgressCluster.
type BackgroundProgressCluster struct {
	ClusterName string                       `json:"clusterName"`
	ClusterUuid uuid.UUID                    `json:"clusterUuid"`
	Databases   []BackgroundProgressDatabase `json:"databases"`
	Error       *string                      `json:"error,omitempty"`
}

// BackgroundProgressDatabase defines model for BackgroundProgressDatabase.
type BackgroundProgressDatabase struct {
	Cdc      SqlExecutionResult `json:"cdc"`
	Database string             `json:"database"`
	Ddl      SqlExecutionResult `json:"ddl"`
}

// BackgroundProgressList defines model for BackgroundProgressList.
type BackgroundProgressList struct {
	Clusters []BackgroundProgressCluster `json:"clusters"`
}

// Cluster defines model for Cluster.
type Cluster struct {
	ClusterName         string           `json:"clusterName"`
	ClusterUuid         uuid.UUID        `json:"clusterUuid"`
	ConnectionStatus    ConnectionStatus `json:"connectionStatus"`
	MetaNodeGrpcUrl     string           `json:"metaNodeGrpcUrl"`
	MetaNodeHttpUrl     string           `json:"metaNodeHttpUrl"`
	SqlConnectionString string           `json:"sqlConnectionString"`
}

// ClusterDatabaseList defines model for ClusterDatabaseList.
type ClusterDatabaseList struct {
	Databases []DatabaseEntry `json:"databases"`
}

// ClusterList defines model for ClusterList.
type ClusterList struct {
	Clusters []Cluster `json:"clusters"`
}

// ClusterRelationList defines model for ClusterRelationList.
type ClusterRelationList struct {
	Categories []RelationCategory `json:"categories"`
}

// ConnectClusterRequest defines model for ConnectClusterRequest.
type ConnectClusterRequest struct {
	ClusterName         string  `json:"clusterName"`
	MetaNodeGrpcUrl     *string `json:"metaNodeGrpcUrl,omitempty"`
	MetaNodeHttpUrl     *string `json:"metaNodeHttpUrl,omitempty"`
	SqlConnectionString string  `json:"sqlConnectionString"`
}

// ConnectClusterResult defines model for ConnectClusterResult.
type ConnectClusterResult struct {
	ClusterUuid uuid.UUID `json:"clusterUuid"`
}

// ConnectionStatus defines model for ConnectionStatus.
type ConnectionStatus struct {
	CheckedAt time.Time     `json:"checkedAt"`
	Meta      EndpointCheck `json:"meta"`
	Sql       EndpointCheck `json:"sql"`
}

// CreateBackgroundDdlRequest defines model for CreateBackgroundDdlRequest.
type CreateBackgroundDdlRequest struct {
	ClusterUuid uuid.UUID `json:"clusterUuid"`
	Database    string    `json:"database"`
	Statement   string    `json:"statement"`
}

// CreateBackgroundDdlResult defines model for CreateBackgroundDdlResult.
type CreateBackgroundDdlResult struct {
	Id     uuid.UUID           `json:"id"`
	Status BackgroundDdlStatus `json:"status"`
}

// CreateNotebookCellRequest defines model for CreateNotebookCellRequest.
type CreateNotebookCellRequest struct {
	BackgroundDdl *bool            `json:"backgroundDdl,omitempty"`
	CellType      NotebookCellType `json:"cellType"`
	ClusterUuid   *uuid.UUID       `json:"clusterUuid,omitempty"`
	Content       string           `json:"content"`
	Database      *string          `json:"database,omitempty"`
}

// CreateNotebookCellResult defines model for CreateNotebookCellResult.
type CreateNotebookCellResult struct {
	CellUuid uuid.UUID `json:"cellUuid"`
}

// CreateNotebookRequest defines model for CreateNotebookRequest.
type CreateNotebookRequest struct {
	NotebookName string `json:"notebookName"`
}

// CreateNotebookResult defines model for CreateNotebookResult.
type CreateNotebookResult struct {
	NotebookUuid uuid.UUID `json:"notebookUuid"`
}

// DatabaseEntry defines model for DatabaseEntry.
type DatabaseEntry struct {
	Name string `json:"name"`
}

// EndpointCheck defines model for EndpointCheck.
type EndpointCheck struct {
	Message string `json:"message"`
	Ok      bool   `json:"ok"`
}

// ExecuteSqlRequest defines model for ExecuteSqlRequest.
type ExecuteSqlRequest struct {
	BackgroundDDL *bool  `json:"backgroundDDL,omitempty"`
	Statement     string `json:"statement"`
}

// Notebook defines model for Notebook.
type Notebook struct {
	Cells        []NotebookCell `json:"cells"`
	NotebookName string         `json:"notebookName"`
	NotebookUuid uuid.UUID      `json:"notebookUuid"`
	UpdatedAt    time.Time      `json:"updatedAt"`
}

// NotebookCell defines model for NotebookCell.
type NotebookCell struct {
	BackgroundDdl bool             `json:"backgroundDdl"`
	CellType      NotebookCellType `json:"cellType"`
	CellUuid      uuid.UUID        `json:"cellUuid"`
	ClusterUuid   *uuid.UUID       `json:"clusterUuid,omitempty"`
	Content       string           `json:"content"`
	Database      *string          `json:"database,omitempty"`
	OrderIndex    int32            `json:"orderIndex"`
	UpdatedAt     time.Time        `json:"updatedAt"`
}

// NotebookList defines model for NotebookList.
type NotebookList struct {
	Notebooks []NotebookSummary `json:"notebooks"`
}

// NotebookSummary defines model for NotebookSummary.
type NotebookSummary struct {
	NotebookName string    `json:"notebookName"`
	NotebookUuid uuid.UUID `json:"notebookUuid"`
	UpdatedAt    time.Time `json:"updatedAt"`
}

// Relation defines model for Relation.
type Relation struct {
	Columns      []RelationColumn `json:"columns"`
	RelationName string           `json:"relationName"`
	RelationType string           `json:"relationType"`
	SchemaName   string           `json:"schemaName"`
}

// RelationCategory defines model for RelationCategory.
type RelationCategory struct {
	Name    string           `json:"name"`
	Schemas []RelationSchema `json:"schemas"`
}

// RelationColumn defines model for RelationColumn.
type RelationColumn struct {
	DataType string `json:"dataType"`
	Name     string `json:"name"`
}

// RelationSchema defines model for RelationSchema.
type RelationSchema struct {
	Relations  []Relation `json:"relations"`
	SchemaName string     `json:"schemaName"`
}

// ReorderNotebookCellsRequest defines model for ReorderNotebookCellsRequest.
type ReorderNotebookCellsRequest struct {
	CellUuids []uuid.UUID `json:"cellUuids"`
}

// SqlExecutionResult defines model for SqlExecutionResult.
type SqlExecutionResult struct {
	Columns    []string `json:"columns"`
	CommandTag string   `json:"commandTag"`
	// SQL execution error returned as a normal response payload.
	Error        *string  `json:"error,omitempty"`
	Rows         []SqlRow `json:"rows"`
	RowsAffected int64    `json:"rowsAffected"`
}

// SqlRow defines model for SqlRow.
type SqlRow struct {
	Values []SqlValue `json:"values"`
}

// SqlValue defines model for SqlValue.
type SqlValue string

// UpdateClusterRequest defines model for UpdateClusterRequest.
type UpdateClusterRequest struct {
	ClusterName         string  `json:"clusterName"`
	MetaNodeGrpcUrl     *string `json:"metaNodeGrpcUrl,omitempty"`
	MetaNodeHttpUrl     *string `json:"metaNodeHttpUrl,omitempty"`
	SqlConnectionString string  `json:"sqlConnectionString"`
}

// UpdateNotebookCellRequest defines model for UpdateNotebookCellRequest.
type UpdateNotebookCellRequest struct {
	BackgroundDdl *bool            `json:"backgroundDdl,omitempty"`
	CellType      NotebookCellType `json:"cellType"`
	ClusterUuid   *uuid.UUID       `json:"clusterUuid,omitempty"`
	Content       string           `json:"content"`
	Database      *string          `json:"database,omitempty"`
}

// BackgroundDdlStatementKind defines enum values
type BackgroundDdlStatementKind string

// BackgroundDdlStatus defines enum values
type BackgroundDdlStatus string

// BackgroundDdlTargetKind defines enum values
type BackgroundDdlTargetKind string

// NotebookCellType defines enum values
type NotebookCellType string

// CreateNotebookJSONRequestBody defines body for CreateNotebook for application/json ContentType.
type CreateNotebookJSONRequestBody = CreateNotebookRequest

// ConnectClusterJSONRequestBody defines body for ConnectCluster for application/json ContentType.
type ConnectClusterJSONRequestBody = ConnectClusterRequest

// CreateBackgroundDdlJSONRequestBody defines body for CreateBackgroundDdl for application/json ContentType.
type CreateBackgroundDdlJSONRequestBody = CreateBackgroundDdlRequest

// ReorderNotebookCellsJSONRequestBody defines body for ReorderNotebookCells for application/json ContentType.
type ReorderNotebookCellsJSONRequestBody = ReorderNotebookCellsRequest

// CreateNotebookCellJSONRequestBody defines body for CreateNotebookCell for application/json ContentType.
type CreateNotebookCellJSONRequestBody = CreateNotebookCellRequest

// UpdateClusterJSONRequestBody defines body for UpdateCluster for application/json ContentType.
type UpdateClusterJSONRequestBody = UpdateClusterRequest

// UpdateNotebookCellJSONRequestBody defines body for UpdateNotebookCell for application/json ContentType.
type UpdateNotebookCellJSONRequestBody = UpdateNotebookCellRequest

// ExecuteClusterSqlJSONRequestBody defines body for ExecuteClusterSql for application/json ContentType.
type ExecuteClusterSqlJSONRequestBody = ExecuteSqlRequest

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	client := Client{Server: server}
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// ListNotebooks request
	ListNotebooks(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateNotebookWithBody request with any body
	CreateNotebookWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateNotebook(ctx context.Context, body CreateNotebookJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ConnectClusterWithBody request with any body
	ConnectClusterWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	ConnectCluster(ctx context.Context, body ConnectClusterJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListClusterBackgroundProgress request
	ListClusterBackgroundProgress(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListClusters request
	ListClusters(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListBackgroundDdls request
	ListBackgroundDdls(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateBackgroundDdlWithBody request with any body
	CreateBackgroundDdlWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateBackgroundDdl(ctx context.Context, body CreateBackgroundDdlJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ReorderNotebookCellsWithBody request with any body
	ReorderNotebookCellsWithBody(ctx context.Context, notebookUuid uuid.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	ReorderNotebookCells(ctx context.Context, notebookUuid uuid.UUID, body ReorderNotebookCellsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateNotebookCellWithBody request with any body
	CreateNotebookCellWithBody(ctx context.Context, notebookUuid uuid.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateNotebookCell(ctx context.Context, notebookUuid uuid.UUID, body CreateNotebookCellJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetNotebook request
	GetNotebook(ctx context.Context, notebookUuid uuid.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteNotebook request
	DeleteNotebook(ctx context.Context, notebookUuid uuid.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListClusterDatabases request
	ListClusterDatabases(ctx context.Context, clusterUuid uuid.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpdateClusterWithBody request with any body
	UpdateClusterWithBody(ctx context.Context, clusterUuid uuid.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	UpdateCluster(ctx context.Context, clusterUuid uuid.UUID, body UpdateClusterJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteCluster request
	DeleteCluster(ctx context.Context, clusterUuid uuid.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteBackgroundDdl request
	DeleteBackgroundDdl(ctx context.Context, id uuid.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpdateNotebookCellWithBody request with any body
	UpdateNotebookCellWithBody(ctx context.Context, notebookUuid uuid.UUID, cellUuid uuid.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	UpdateNotebookCell(ctx context.Context, notebookUuid uuid.UUID, cellUuid uuid.UUID, body UpdateNotebookCellJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteNotebookCell request
	DeleteNotebookCell(ctx context.Context, notebookUuid uuid.UUID, cellUuid uuid.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ExecuteClusterSqlWithBody request with any body
	ExecuteClusterSqlWithBody(ctx context.Context, clusterUuid uuid.UUID, database string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	ExecuteClusterSql(ctx context.Context, clusterUuid uuid.UUID, database string, body ExecuteClusterSqlJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListClusterRelations request
	ListClusterRelations(ctx context.Context, clusterUuid uuid.UUID, database string, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) ListNotebooks(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListNotebooksRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateNotebookWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateNotebookRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateNotebook(ctx context.Context, body CreateNotebookJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	bodyBytes, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	return c.CreateNotebookWithBody(ctx, "application/json", bytes.NewReader(bodyBytes), reqEditors...)
}

func (c *Client) ConnectClusterWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewConnectClusterRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ConnectCluster(ctx context.Context, body ConnectClusterJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	bodyBytes, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	return c.ConnectClusterWithBody(ctx, "application/json", bytes.NewReader(bodyBytes), reqEditors...)
}

func (c *Client) ListClusterBackgroundProgress(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListClusterBackgroundProgressRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListClusters(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListClustersRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListBackgroundDdls(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListBackgroundDdlsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateBackgroundDdlWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateBackgroundDdlRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateBackgroundDdl(ctx context.Context, body CreateBackgroundDdlJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	bodyBytes, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	return c.CreateBackgroundDdlWithBody(ctx, "application/json", bytes.NewReader(bodyBytes), reqEditors...)
}

func (c *Client) ReorderNotebookCellsWithBody(ctx context.Context, notebookUuid uuid.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewReorderNotebookCellsRequestWithBody(c.Server, notebookUuid, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ReorderNotebookCells(ctx context.Context, notebookUuid uuid.UUID, body ReorderNotebookCellsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	bodyBytes, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	return c.ReorderNotebookCellsWithBody(ctx, notebookUuid, "application/json", bytes.NewReader(bodyBytes), reqEditors...)
}

func (c *Client) CreateNotebookCellWithBody(ctx context.Context, notebookUuid uuid.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateNotebookCellRequestWithBody(c.Server, notebookUuid, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateNotebookCell(ctx context.Context, notebookUuid uuid.UUID, body CreateNotebookCellJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	bodyBytes, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	return c.CreateNotebookCellWithBody(ctx, notebookUuid, "application/json", bytes.NewReader(bodyBytes), reqEditors...)
}

func (c *Client) GetNotebook(ctx context.Context, notebookUuid uuid.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetNotebookRequest(c.Server, notebookUuid)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteNotebook(ctx context.Context, notebookUuid uuid.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteNotebookRequest(c.Server, notebookUuid)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListClusterDatabases(ctx context.Context, clusterUuid uuid.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListClusterDatabasesRequest(c.Server, clusterUuid)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateClusterWithBody(ctx context.Context, clusterUuid uuid.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateClusterRequestWithBody(c.Server, clusterUuid, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateCluster(ctx context.Context, clusterUuid uuid.UUID, body UpdateClusterJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	bodyBytes, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	return c.UpdateClusterWithBody(ctx, clusterUuid, "application/json", bytes.NewReader(bodyBytes), reqEditors...)
}

func (c *Client) DeleteCluster(ctx context.Context, clusterUuid uuid.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteClusterRequest(c.Server, clusterUuid)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteBackgroundDdl(ctx context.Context, id uuid.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteBackgroundDdlRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateNotebookCellWithBody(ctx context.Context, notebookUuid uuid.UUID, cellUuid uuid.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateNotebookCellRequestWithBody(c.Server, notebookUuid, cellUuid, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateNotebookCell(ctx context.Context, notebookUuid uuid.UUID, cellUuid uuid.UUID, body UpdateNotebookCellJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	bodyBytes, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	return c.UpdateNotebookCellWithBody(ctx, notebookUuid, cellUuid, "application/json", bytes.NewReader(bodyBytes), reqEditors...)
}

func (c *Client) DeleteNotebookCell(ctx context.Context, notebookUuid uuid.UUID, cellUuid uuid.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteNotebookCellRequest(c.Server, notebookUuid, cellUuid)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ExecuteClusterSqlWithBody(ctx context.Context, clusterUuid uuid.UUID, database string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewExecuteClusterSqlRequestWithBody(c.Server, clusterUuid, database, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ExecuteClusterSql(ctx context.Context, clusterUuid uuid.UUID, database string, body ExecuteClusterSqlJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	bodyBytes, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	return c.ExecuteClusterSqlWithBody(ctx, clusterUuid, database, "application/json", bytes.NewReader(bodyBytes), reqEditors...)
}

func (c *Client) ListClusterRelations(ctx context.Context, clusterUuid uuid.UUID, database string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListClusterRelationsRequest(c.Server, clusterUuid, database)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewListNotebooksRequest generates requests for ListNotebooks
func NewListNotebooksRequest(server string) (*http.Request, error) {
	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/notebooks")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}

// NewCreateNotebookRequestWithBody generates requests for CreateNotebook with any body
func NewCreateNotebookRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/notebooks")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", contentType)
	return req, nil
}

// NewCreateNotebookRequest generates requests for CreateNotebook
func NewCreateNotebookRequest(server string, body CreateNotebookJSONRequestBody) (*http.Request, error) {
	bodyBytes, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	return NewCreateNotebookRequestWithBody(server, "application/json", bytes.NewReader(bodyBytes))
}

// NewConnectClusterRequestWithBody generates requests for ConnectCluster with any body
func NewConnectClusterRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/clusters/connect")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", contentType)
	return req, nil
}

// NewConnectClusterRequest generates requests for ConnectCluster
func NewConnectClusterRequest(server string, body ConnectClusterJSONRequestBody) (*http.Request, error) {
	bodyBytes, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	return NewConnectClusterRequestWithBody(server, "application/json", bytes.NewReader(bodyBytes))
}

// NewListClusterBackgroundProgressRequest generates requests for ListClusterBackgroundProgress
func NewListClusterBackgroundProgressRequest(server string) (*http.Request, error) {
	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/clusters/background-progress")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}

// NewListClustersRequest generates requests for ListClusters
func NewListClustersRequest(server string) (*http.Request, error) {
	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/clusters")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}

// NewListBackgroundDdlsRequest generates requests for ListBackgroundDdls
func NewListBackgroundDdlsRequest(server string) (*http.Request, error) {
	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/background-ddls")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}

// NewCreateBackgroundDdlRequestWithBody generates requests for CreateBackgroundDdl with any body
func NewCreateBackgroundDdlRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/background-ddls")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", contentType)
	return req, nil
}

// NewCreateBackgroundDdlRequest generates requests for CreateBackgroundDdl
func NewCreateBackgroundDdlRequest(server string, body CreateBackgroundDdlJSONRequestBody) (*http.Request, error) {
	bodyBytes, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	return NewCreateBackgroundDdlRequestWithBody(server, "application/json", bytes.NewReader(bodyBytes))
}

// NewReorderNotebookCellsRequestWithBody generates requests for ReorderNotebookCells with any body
func NewReorderNotebookCellsRequestWithBody(server string, notebookUuid uuid.UUID, contentType string, body io.Reader) (*http.Request, error) {
	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/notebooks/%v/cells/order", notebookUuid)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", contentType)
	return req, nil
}

// NewReorderNotebookCellsRequest generates requests for ReorderNotebookCells
func NewReorderNotebookCellsRequest(server string, notebookUuid uuid.UUID, body ReorderNotebookCellsJSONRequestBody) (*http.Request, error) {
	bodyBytes, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	return NewReorderNotebookCellsRequestWithBody(server, notebookUuid, "application/json", bytes.NewReader(bodyBytes))
}

// NewCreateNotebookCellRequestWithBody generates requests for CreateNotebookCell with any body
func NewCreateNotebookCellRequestWithBody(server string, notebookUuid uuid.UUID, contentType string, body io.Reader) (*http.Request, error) {
	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/notebooks/%v/cells", notebookUuid)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", contentType)
	return req, nil
}

// NewCreateNotebookCellRequest generates requests for CreateNotebookCell
func NewCreateNotebookCellRequest(server string, notebookUuid uuid.UUID, body CreateNotebookCellJSONRequestBody) (*http.Request, error) {
	bodyBytes, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	return NewCreateNotebookCellRequestWithBody(server, notebookUuid, "application/json", bytes.NewReader(bodyBytes))
}

// NewGetNotebookRequest generates requests for GetNotebook
func NewGetNotebookRequest(server string, notebookUuid uuid.UUID) (*http.Request, error) {
	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/notebooks/%v", notebookUuid)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}

// NewDeleteNotebookRequest generates requests for DeleteNotebook
func NewDeleteNotebookRequest(server string, notebookUuid uuid.UUID) (*http.Request, error) {
	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/notebooks/%v", notebookUuid)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}

// NewListClusterDatabasesRequest generates requests for ListClusterDatabases
func NewListClusterDatabasesRequest(server string, clusterUuid uuid.UUID) (*http.Request, error) {
	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/clusters/%v/databases", clusterUuid)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}

// NewUpdateClusterRequestWithBody generates requests for UpdateCluster with any body
func NewUpdateClusterRequestWithBody(server string, clusterUuid uuid.UUID, contentType string, body io.Reader) (*http.Request, error) {
	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/clusters/%v", clusterUuid)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", contentType)
	return req, nil
}

// NewUpdateClusterRequest generates requests for UpdateCluster
func NewUpdateClusterRequest(server string, clusterUuid uuid.UUID, body UpdateClusterJSONRequestBody) (*http.Request, error) {
	bodyBytes, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	return NewUpdateClusterRequestWithBody(server, clusterUuid, "application/json", bytes.NewReader(bodyBytes))
}

// NewDeleteClusterRequest generates requests for DeleteCluster
func NewDeleteClusterRequest(server string, clusterUuid uuid.UUID) (*http.Request, error) {
	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/clusters/%v", clusterUuid)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}

// NewDeleteBackgroundDdlRequest generates requests for DeleteBackgroundDdl
func NewDeleteBackgroundDdlRequest(server string, id uuid.UUID) (*http.Request, error) {
	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/background-ddls/%v", id)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}

// NewUpdateNotebookCellRequestWithBody generates requests for UpdateNotebookCell with any body
func NewUpdateNotebookCellRequestWithBody(server string, notebookUuid uuid.UUID, cellUuid uuid.UUID, contentType string, body io.Reader) (*http.Request, error) {
	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/notebooks/%v/cells/%v", notebookUuid, cellUuid)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", contentType)
	return req, nil
}

// NewUpdateNotebookCellRequest generates requests for UpdateNotebookCell
func NewUpdateNotebookCellRequest(server string, notebookUuid uuid.UUID, cellUuid uuid.UUID, body UpdateNotebookCellJSONRequestBody) (*http.Request, error) {
	bodyBytes, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	return NewUpdateNotebookCellRequestWithBody(server, notebookUuid, cellUuid, "application/json", bytes.NewReader(bodyBytes))
}

// NewDeleteNotebookCellRequest generates requests for DeleteNotebookCell
func NewDeleteNotebookCellRequest(server string, notebookUuid uuid.UUID, cellUuid uuid.UUID) (*http.Request, error) {
	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/notebooks/%v/cells/%v", notebookUuid, cellUuid)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}

// NewExecuteClusterSqlRequestWithBody generates requests for ExecuteClusterSql with any body
func NewExecuteClusterSqlRequestWithBody(server string, clusterUuid uuid.UUID, database string, contentType string, body io.Reader) (*http.Request, error) {
	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/clusters/%v/%v/sql", clusterUuid, database)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", contentType)
	return req, nil
}

// NewExecuteClusterSqlRequest generates requests for ExecuteClusterSql
func NewExecuteClusterSqlRequest(server string, clusterUuid uuid.UUID, database string, body ExecuteClusterSqlJSONRequestBody) (*http.Request, error) {
	bodyBytes, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	return NewExecuteClusterSqlRequestWithBody(server, clusterUuid, database, "application/json", bytes.NewReader(bodyBytes))
}

// NewListClusterRelationsRequest generates requests for ListClusterRelations
func NewListClusterRelationsRequest(server string, clusterUuid uuid.UUID, database string) (*http.Request, error) {
	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/clusters/%v/%v/relations", clusterUuid, database)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// ListNotebooksWithResponse request
	ListNotebooksWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListNotebooksResponse, error)

	// CreateNotebookWithBodyWithResponse request with any body
	CreateNotebookWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateNotebookResponse, error)

	CreateNotebookWithResponse(ctx context.Context, body CreateNotebookJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateNotebookResponse, error)

	// ConnectClusterWithBodyWithResponse request with any body
	ConnectClusterWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ConnectClusterResponse, error)

	ConnectClusterWithResponse(ctx context.Context, body ConnectClusterJSONRequestBody, reqEditors ...RequestEditorFn) (*ConnectClusterResponse, error)

	// ListClusterBackgroundProgressWithResponse request
	ListClusterBackgroundProgressWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListClusterBackgroundProgressResponse, error)

	// ListClustersWithResponse request
	ListClustersWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListClustersResponse, error)

	// ListBackgroundDdlsWithResponse request
	ListBackgroundDdlsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListBackgroundDdlsResponse, error)

	// CreateBackgroundDdlWithBodyWithResponse request with any body
	CreateBackgroundDdlWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateBackgroundDdlResponse, error)

	CreateBackgroundDdlWithResponse(ctx context.Context, body CreateBackgroundDdlJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateBackgroundDdlResponse, error)

	// ReorderNotebookCellsWithBodyWithResponse request with any body
	ReorderNotebookCellsWithBodyWithResponse(ctx context.Context, notebookUuid uuid.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ReorderNotebookCellsResponse, error)

	ReorderNotebookCellsWithResponse(ctx context.Context, notebookUuid uuid.UUID, body ReorderNotebookCellsJSONRequestBody, reqEditors ...RequestEditorFn) (*ReorderNotebookCellsResponse, error)

	// CreateNotebookCellWithBodyWithResponse request with any body
	CreateNotebookCellWithBodyWithResponse(ctx context.Context, notebookUuid uuid.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateNotebookCellResponse, error)

	CreateNotebookCellWithResponse(ctx context.Context, notebookUuid uuid.UUID, body CreateNotebookCellJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateNotebookCellResponse, error)

	// GetNotebookWithResponse request
	GetNotebookWithResponse(ctx context.Context, notebookUuid uuid.UUID, reqEditors ...RequestEditorFn) (*GetNotebookResponse, error)

	// DeleteNotebookWithResponse request
	DeleteNotebookWithResponse(ctx context.Context, notebookUuid uuid.UUID, reqEditors ...RequestEditorFn) (*DeleteNotebookResponse, error)

	// ListClusterDatabasesWithResponse request
	ListClusterDatabasesWithResponse(ctx context.Context, clusterUuid uuid.UUID, reqEditors ...RequestEditorFn) (*ListClusterDatabasesResponse, error)

	// UpdateClusterWithBodyWithResponse request with any body
	UpdateClusterWithBodyWithResponse(ctx context.Context, clusterUuid uuid.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateClusterResponse, error)

	UpdateClusterWithResponse(ctx context.Context, clusterUuid uuid.UUID, body UpdateClusterJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateClusterResponse, error)

	// DeleteClusterWithResponse request
	DeleteClusterWithResponse(ctx context.Context, clusterUuid uuid.UUID, reqEditors ...RequestEditorFn) (*DeleteClusterResponse, error)

	// DeleteBackgroundDdlWithResponse request
	DeleteBackgroundDdlWithResponse(ctx context.Context, id uuid.UUID, reqEditors ...RequestEditorFn) (*DeleteBackgroundDdlResponse, error)

	// UpdateNotebookCellWithBodyWithResponse request with any body
	UpdateNotebookCellWithBodyWithResponse(ctx context.Context, notebookUuid uuid.UUID, cellUuid uuid.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateNotebookCellResponse, error)

	UpdateNotebookCellWithResponse(ctx context.Context, notebookUuid uuid.UUID, cellUuid uuid.UUID, body UpdateNotebookCellJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateNotebookCellResponse, error)

	// DeleteNotebookCellWithResponse request
	DeleteNotebookCellWithResponse(ctx context.Context, notebookUuid uuid.UUID, cellUuid uuid.UUID, reqEditors ...RequestEditorFn) (*DeleteNotebookCellResponse, error)

	// ExecuteClusterSqlWithBodyWithResponse request with any body
	ExecuteClusterSqlWithBodyWithResponse(ctx context.Context, clusterUuid uuid.UUID, database string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ExecuteClusterSqlResponse, error)

	ExecuteClusterSqlWithResponse(ctx context.Context, clusterUuid uuid.UUID, database string, body ExecuteClusterSqlJSONRequestBody, reqEditors ...RequestEditorFn) (*ExecuteClusterSqlResponse, error)

	// ListClusterRelationsWithResponse request
	ListClusterRelationsWithResponse(ctx context.Context, clusterUuid uuid.UUID, database string, reqEditors ...RequestEditorFn) (*ListClusterRelationsResponse, error)
}

type ListNotebooksResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *NotebookList
}

// Status returns HTTPResponse.Status
func (r ListNotebooksResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListNotebooksResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateNotebookResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *CreateNotebookResult
}

// Status returns HTTPResponse.Status
func (r CreateNotebookResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateNotebookResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ConnectClusterResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ConnectClusterResult
}

// Status returns HTTPResponse.Status
func (r ConnectClusterResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ConnectClusterResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListClusterBackgroundProgressResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *BackgroundProgressList
}

// Status returns HTTPResponse.Status
func (r ListClusterBackgroundProgressResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListClusterBackgroundProgressResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListClustersResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ClusterList
}

// Status returns HTTPResponse.Status
func (r ListClustersResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListClustersResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListBackgroundDdlsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *BackgroundDdlList
}

// Status returns HTTPResponse.Status
func (r ListBackgroundDdlsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListBackgroundDdlsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateBackgroundDdlResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON202      *CreateBackgroundDdlResult
}

// Status returns HTTPResponse.Status
func (r CreateBackgroundDdlResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateBackgroundDdlResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ReorderNotebookCellsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r ReorderNotebookCellsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ReorderNotebookCellsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateNotebookCellResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *CreateNotebookCellResult
}

// Status returns HTTPResponse.Status
func (r CreateNotebookCellResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateNotebookCellResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetNotebookResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Notebook
}

// Status returns HTTPResponse.Status
func (r GetNotebookResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetNotebookResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteNotebookResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r DeleteNotebookResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteNotebookResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListClusterDatabasesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ClusterDatabaseList
}

// Status returns HTTPResponse.Status
func (r ListClusterDatabasesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListClusterDatabasesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type UpdateClusterResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Cluster
}

// Status returns HTTPResponse.Status
func (r UpdateClusterResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UpdateClusterResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteClusterResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r DeleteClusterResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteClusterResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteBackgroundDdlResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r DeleteBackgroundDdlResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteBackgroundDdlResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type UpdateNotebookCellResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *NotebookCell
}

// Status returns HTTPResponse.Status
func (r UpdateNotebookCellResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UpdateNotebookCellResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteNotebookCellResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r DeleteNotebookCellResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteNotebookCellResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ExecuteClusterSqlResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *SqlExecutionResult
}

// Status returns HTTPResponse.Status
func (r ExecuteClusterSqlResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ExecuteClusterSqlResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListClusterRelationsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ClusterRelationList
}

// Status returns HTTPResponse.Status
func (r ListClusterRelationsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListClusterRelationsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ListNotebooksWithResponse request returning *ListNotebooksResponse
func (c *ClientWithResponses) ListNotebooksWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListNotebooksResponse, error) {
	rsp, err := c.ListNotebooks(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListNotebooksResponse(rsp)
}

// CreateNotebookWithBodyWithResponse request with arbitrary body returning *CreateNotebookResponse
func (c *ClientWithResponses) CreateNotebookWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateNotebookResponse, error) {
	rsp, err := c.CreateNotebookWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateNotebookResponse(rsp)
}

func (c *ClientWithResponses) CreateNotebookWithResponse(ctx context.Context, body CreateNotebookJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateNotebookResponse, error) {
	rsp, err := c.CreateNotebook(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateNotebookResponse(rsp)
}

// ConnectClusterWithBodyWithResponse request with arbitrary body returning *ConnectClusterResponse
func (c *ClientWithResponses) ConnectClusterWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ConnectClusterResponse, error) {
	rsp, err := c.ConnectClusterWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseConnectClusterResponse(rsp)
}

func (c *ClientWithResponses) ConnectClusterWithResponse(ctx context.Context, body ConnectClusterJSONRequestBody, reqEditors ...RequestEditorFn) (*ConnectClusterResponse, error) {
	rsp, err := c.ConnectCluster(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseConnectClusterResponse(rsp)
}

// ListClusterBackgroundProgressWithResponse request returning *ListClusterBackgroundProgressResponse
func (c *ClientWithResponses) ListClusterBackgroundProgressWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListClusterBackgroundProgressResponse, error) {
	rsp, err := c.ListClusterBackgroundProgress(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListClusterBackgroundProgressResponse(rsp)
}

// ListClustersWithResponse request returning *ListClustersResponse
func (c *ClientWithResponses) ListClustersWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListClustersResponse, error) {
	rsp, err := c.ListClusters(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListClustersResponse(rsp)
}

// ListBackgroundDdlsWithResponse request returning *ListBackgroundDdlsResponse
func (c *ClientWithResponses) ListBackgroundDdlsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListBackgroundDdlsResponse, error) {
	rsp, err := c.ListBackgroundDdls(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListBackgroundDdlsResponse(rsp)
}

// CreateBackgroundDdlWithBodyWithResponse request with arbitrary body returning *CreateBackgroundDdlResponse
func (c *ClientWithResponses) CreateBackgroundDdlWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateBackgroundDdlResponse, error) {
	rsp, err := c.CreateBackgroundDdlWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateBackgroundDdlResponse(rsp)
}

func (c *ClientWithResponses) CreateBackgroundDdlWithResponse(ctx context.Context, body CreateBackgroundDdlJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateBackgroundDdlResponse, error) {
	rsp, err := c.CreateBackgroundDdl(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateBackgroundDdlResponse(rsp)
}

// ReorderNotebookCellsWithBodyWithResponse request with arbitrary body returning *ReorderNotebookCellsResponse
func (c *ClientWithResponses) ReorderNotebookCellsWithBodyWithResponse(ctx context.Context, notebookUuid uuid.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ReorderNotebookCellsResponse, error) {
	rsp, err := c.ReorderNotebookCellsWithBody(ctx, notebookUuid, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseReorderNotebookCellsResponse(rsp)
}

func (c *ClientWithResponses) ReorderNotebookCellsWithResponse(ctx context.Context, notebookUuid uuid.UUID, body ReorderNotebookCellsJSONRequestBody, reqEditors ...RequestEditorFn) (*ReorderNotebookCellsResponse, error) {
	rsp, err := c.ReorderNotebookCells(ctx, notebookUuid, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseReorderNotebookCellsResponse(rsp)
}

// CreateNotebookCellWithBodyWithResponse request with arbitrary body returning *CreateNotebookCellResponse
func (c *ClientWithResponses) CreateNotebookCellWithBodyWithResponse(ctx context.Context, notebookUuid uuid.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateNotebookCellResponse, error) {
	rsp, err := c.CreateNotebookCellWithBody(ctx, notebookUuid, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateNotebookCellResponse(rsp)
}

func (c *ClientWithResponses) CreateNotebookCellWithResponse(ctx context.Context, notebookUuid uuid.UUID, body CreateNotebookCellJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateNotebookCellResponse, error) {
	rsp, err := c.CreateNotebookCell(ctx, notebookUuid, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateNotebookCellResponse(rsp)
}

// GetNotebookWithResponse request returning *GetNotebookResponse
func (c *ClientWithResponses) GetNotebookWithResponse(ctx context.Context, notebookUuid uuid.UUID, reqEditors ...RequestEditorFn) (*GetNotebookResponse, error) {
	rsp, err := c.GetNotebook(ctx, notebookUuid, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetNotebookResponse(rsp)
}

// DeleteNotebookWithResponse request returning *DeleteNotebookResponse
func (c *ClientWithResponses) DeleteNotebookWithResponse(ctx context.Context, notebookUuid uuid.UUID, reqEditors ...RequestEditorFn) (*DeleteNotebookResponse, error) {
	rsp, err := c.DeleteNotebook(ctx, notebookUuid, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteNotebookResponse(rsp)
}

// ListClusterDatabasesWithResponse request returning *ListClusterDatabasesResponse
func (c *ClientWithResponses) ListClusterDatabasesWithResponse(ctx context.Context, clusterUuid uuid.UUID, reqEditors ...RequestEditorFn) (*ListClusterDatabasesResponse, error) {
	rsp, err := c.ListClusterDatabases(ctx, clusterUuid, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListClusterDatabasesResponse(rsp)
}

// UpdateClusterWithBodyWithResponse request with arbitrary body returning *UpdateClusterResponse
func (c *ClientWithResponses) UpdateClusterWithBodyWithResponse(ctx context.Context, clusterUuid uuid.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateClusterResponse, error) {
	rsp, err := c.UpdateClusterWithBody(ctx, clusterUuid, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateClusterResponse(rsp)
}

func (c *ClientWithResponses) UpdateClusterWithResponse(ctx context.Context, clusterUuid uuid.UUID, body UpdateClusterJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateClusterResponse, error) {
	rsp, err := c.UpdateCluster(ctx, clusterUuid, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateClusterResponse(rsp)
}

// DeleteClusterWithResponse request returning *DeleteClusterResponse
func (c *ClientWithResponses) DeleteClusterWithResponse(ctx context.Context, clusterUuid uuid.UUID, reqEditors ...RequestEditorFn) (*DeleteClusterResponse, error) {
	rsp, err := c.DeleteCluster(ctx, clusterUuid, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteClusterResponse(rsp)
}

// DeleteBackgroundDdlWithResponse request returning *DeleteBackgroundDdlResponse
func (c *ClientWithResponses) DeleteBackgroundDdlWithResponse(ctx context.Context, id uuid.UUID, reqEditors ...RequestEditorFn) (*DeleteBackgroundDdlResponse, error) {
	rsp, err := c.DeleteBackgroundDdl(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteBackgroundDdlResponse(rsp)
}

// UpdateNotebookCellWithBodyWithResponse request with arbitrary body returning *UpdateNotebookCellResponse
func (c *ClientWithResponses) UpdateNotebookCellWithBodyWithResponse(ctx context.Context, notebookUuid uuid.UUID, cellUuid uuid.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateNotebookCellResponse, error) {
	rsp, err := c.UpdateNotebookCellWithBody(ctx, notebookUuid, cellUuid, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateNotebookCellResponse(rsp)
}

func (c *ClientWithResponses) UpdateNotebookCellWithResponse(ctx context.Context, notebookUuid uuid.UUID, cellUuid uuid.UUID, body UpdateNotebookCellJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateNotebookCellResponse, error) {
	rsp, err := c.UpdateNotebookCell(ctx, notebookUuid, cellUuid, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateNotebookCellResponse(rsp)
}

// DeleteNotebookCellWithResponse request returning *DeleteNotebookCellResponse
func (c *ClientWithResponses) DeleteNotebookCellWithResponse(ctx context.Context, notebookUuid uuid.UUID, cellUuid uuid.UUID, reqEditors ...RequestEditorFn) (*DeleteNotebookCellResponse, error) {
	rsp, err := c.DeleteNotebookCell(ctx, notebookUuid, cellUuid, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteNotebookCellResponse(rsp)
}

// ExecuteClusterSqlWithBodyWithResponse request with arbitrary body returning *ExecuteClusterSqlResponse
func (c *ClientWithResponses) ExecuteClusterSqlWithBodyWithResponse(ctx context.Context, clusterUuid uuid.UUID, database string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ExecuteClusterSqlResponse, error) {
	rsp, err := c.ExecuteClusterSqlWithBody(ctx, clusterUuid, database, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseExecuteClusterSqlResponse(rsp)
}

func (c *ClientWithResponses) ExecuteClusterSqlWithResponse(ctx context.Context, clusterUuid uuid.UUID, database string, body ExecuteClusterSqlJSONRequestBody, reqEditors ...RequestEditorFn) (*ExecuteClusterSqlResponse, error) {
	rsp, err := c.ExecuteClusterSql(ctx, clusterUuid, database, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseExecuteClusterSqlResponse(rsp)
}

// ListClusterRelationsWithResponse request returning *ListClusterRelationsResponse
func (c *ClientWithResponses) ListClusterRelationsWithResponse(ctx context.Context, clusterUuid uuid.UUID, database string, reqEditors ...RequestEditorFn) (*ListClusterRelationsResponse, error) {
	rsp, err := c.ListClusterRelations(ctx, clusterUuid, database, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListClusterRelationsResponse(rsp)
}

// ParseListNotebooksResponse parses an HTTP response from a ListNotebooksWithResponse call
func ParseListNotebooksResponse(rsp *http.Response) (*ListNotebooksResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListNotebooksResponse{Body: bodyBytes, HTTPResponse: rsp}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest NotebookList
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest
	}

	return response, nil
}

// ParseCreateNotebookResponse parses an HTTP response from a CreateNotebookWithResponse call
func ParseCreateNotebookResponse(rsp *http.Response) (*CreateNotebookResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateNotebookResponse{Body: bodyBytes, HTTPResponse: rsp}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest CreateNotebookResult
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest
	}

	return response, nil
}

// ParseConnectClusterResponse parses an HTTP response from a ConnectClusterWithResponse call
func ParseConnectClusterResponse(rsp *http.Response) (*ConnectClusterResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ConnectClusterResponse{Body: bodyBytes, HTTPResponse: rsp}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ConnectClusterResult
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest
	}

	return response, nil
}

// ParseListClusterBackgroundProgressResponse parses an HTTP response from a ListClusterBackgroundProgressWithResponse call
func ParseListClusterBackgroundProgressResponse(rsp *http.Response) (*ListClusterBackgroundProgressResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListClusterBackgroundProgressResponse{Body: bodyBytes, HTTPResponse: rsp}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest BackgroundProgressList
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest
	}

	return response, nil
}

// ParseListClustersResponse parses an HTTP response from a ListClustersWithResponse call
func ParseListClustersResponse(rsp *http.Response) (*ListClustersResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListClustersResponse{Body: bodyBytes, HTTPResponse: rsp}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ClusterList
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest
	}

	return response, nil
}

// ParseListBackgroundDdlsResponse parses an HTTP response from a ListBackgroundDdlsWithResponse call
func ParseListBackgroundDdlsResponse(rsp *http.Response) (*ListBackgroundDdlsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListBackgroundDdlsResponse{Body: bodyBytes, HTTPResponse: rsp}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest BackgroundDdlList
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest
	}

	return response, nil
}

// ParseCreateBackgroundDdlResponse parses an HTTP response from a CreateBackgroundDdlWithResponse call
func ParseCreateBackgroundDdlResponse(rsp *http.Response) (*CreateBackgroundDdlResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateBackgroundDdlResponse{Body: bodyBytes, HTTPResponse: rsp}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 202:
		var dest CreateBackgroundDdlResult
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON202 = &dest
	}

	return response, nil
}

// ParseReorderNotebookCellsResponse parses an HTTP response from a ReorderNotebookCellsWithResponse call
func ParseReorderNotebookCellsResponse(rsp *http.Response) (*ReorderNotebookCellsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ReorderNotebookCellsResponse{Body: bodyBytes, HTTPResponse: rsp}

	return response, nil
}

// ParseCreateNotebookCellResponse parses an HTTP response from a CreateNotebookCellWithResponse call
func ParseCreateNotebookCellResponse(rsp *http.Response) (*CreateNotebookCellResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateNotebookCellResponse{Body: bodyBytes, HTTPResponse: rsp}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest CreateNotebookCellResult
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest
	}

	return response, nil
}

// ParseGetNotebookResponse parses an HTTP response from a GetNotebookWithResponse call
func ParseGetNotebookResponse(rsp *http.Response) (*GetNotebookResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetNotebookResponse{Body: bodyBytes, HTTPResponse: rsp}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Notebook
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest
	}

	return response, nil
}

// ParseDeleteNotebookResponse parses an HTTP response from a DeleteNotebookWithResponse call
func ParseDeleteNotebookResponse(rsp *http.Response) (*DeleteNotebookResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteNotebookResponse{Body: bodyBytes, HTTPResponse: rsp}

	return response, nil
}

// ParseListClusterDatabasesResponse parses an HTTP response from a ListClusterDatabasesWithResponse call
func ParseListClusterDatabasesResponse(rsp *http.Response) (*ListClusterDatabasesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListClusterDatabasesResponse{Body: bodyBytes, HTTPResponse: rsp}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ClusterDatabaseList
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest
	}

	return response, nil
}

// ParseUpdateClusterResponse parses an HTTP response from a UpdateClusterWithResponse call
func ParseUpdateClusterResponse(rsp *http.Response) (*UpdateClusterResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UpdateClusterResponse{Body: bodyBytes, HTTPResponse: rsp}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Cluster
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest
	}

	return response, nil
}

// ParseDeleteClusterResponse parses an HTTP response from a DeleteClusterWithResponse call
func ParseDeleteClusterResponse(rsp *http.Response) (*DeleteClusterResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteClusterResponse{Body: bodyBytes, HTTPResponse: rsp}

	return response, nil
}

// ParseDeleteBackgroundDdlResponse parses an HTTP response from a DeleteBackgroundDdlWithResponse call
func ParseDeleteBackgroundDdlResponse(rsp *http.Response) (*DeleteBackgroundDdlResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteBackgroundDdlResponse{Body: bodyBytes, HTTPResponse: rsp}

	return response, nil
}

// ParseUpdateNotebookCellResponse parses an HTTP response from a UpdateNotebookCellWithResponse call
func ParseUpdateNotebookCellResponse(rsp *http.Response) (*UpdateNotebookCellResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UpdateNotebookCellResponse{Body: bodyBytes, HTTPResponse: rsp}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest NotebookCell
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest
	}

	return response, nil
}

// ParseDeleteNotebookCellResponse parses an HTTP response from a DeleteNotebookCellWithResponse call
func ParseDeleteNotebookCellResponse(rsp *http.Response) (*DeleteNotebookCellResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteNotebookCellResponse{Body: bodyBytes, HTTPResponse: rsp}

	return response, nil
}

// ParseExecuteClusterSqlResponse parses an HTTP response from a ExecuteClusterSqlWithResponse call
func ParseExecuteClusterSqlResponse(rsp *http.Response) (*ExecuteClusterSqlResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ExecuteClusterSqlResponse{Body: bodyBytes, HTTPResponse: rsp}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest SqlExecutionResult
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest
	}

	return response, nil
}

// ParseListClusterRelationsResponse parses an HTTP response from a ListClusterRelationsWithResponse call
func ParseListClusterRelationsResponse(rsp *http.Response) (*ListClusterRelationsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListClusterRelationsResponse{Body: bodyBytes, HTTPResponse: rsp}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ClusterRelationList
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest
	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List notebooks
	// (GET /notebooks)
	ListNotebooks(c fiber.Ctx) error
	// Create notebook
	// (POST /notebooks)
	CreateNotebook(c fiber.Ctx) error
	// Connect a RisingWave cluster
	// (POST /clusters/connect)
	ConnectCluster(c fiber.Ctx) error
	// List background DDL and CDC progress across all clusters and databases
	// (GET /clusters/background-progress)
	ListClusterBackgroundProgress(c fiber.Ctx) error
	// List connected clusters
	// (GET /clusters)
	ListClusters(c fiber.Ctx) error
	// List background DDL jobs with statement progress
	// (GET /background-ddls)
	ListBackgroundDdls(c fiber.Ctx) error
	// Create a background DDL job
	// (POST /background-ddls)
	CreateBackgroundDdl(c fiber.Ctx) error
	// Reorder notebook cells
	// (POST /notebooks/{notebook_uuid}/cells/order)
	ReorderNotebookCells(c fiber.Ctx, notebookUuid uuid.UUID) error
	// Create notebook cell
	// (POST /notebooks/{notebook_uuid}/cells)
	CreateNotebookCell(c fiber.Ctx, notebookUuid uuid.UUID) error
	// Get notebook content
	// (GET /notebooks/{notebook_uuid})
	GetNotebook(c fiber.Ctx, notebookUuid uuid.UUID) error
	// Delete notebook
	// (DELETE /notebooks/{notebook_uuid})
	DeleteNotebook(c fiber.Ctx, notebookUuid uuid.UUID) error
	// List databases for a cluster
	// (GET /clusters/{cluster_uuid}/databases)
	ListClusterDatabases(c fiber.Ctx, clusterUuid uuid.UUID) error
	// Update cluster settings
	// (PUT /clusters/{cluster_uuid})
	UpdateCluster(c fiber.Ctx, clusterUuid uuid.UUID) error
	// Delete a cluster connection
	// (DELETE /clusters/{cluster_uuid})
	DeleteCluster(c fiber.Ctx, clusterUuid uuid.UUID) error
	// Cancel a background DDL job
	// (DELETE /background-ddls/{id})
	DeleteBackgroundDdl(c fiber.Ctx, id uuid.UUID) error
	// Update notebook cell
	// (PUT /notebooks/{notebook_uuid}/cells/{cell_uuid})
	UpdateNotebookCell(c fiber.Ctx, notebookUuid uuid.UUID, cellUuid uuid.UUID) error
	// Delete notebook cell
	// (DELETE /notebooks/{notebook_uuid}/cells/{cell_uuid})
	DeleteNotebookCell(c fiber.Ctx, notebookUuid uuid.UUID, cellUuid uuid.UUID) error
	// Execute SQL against a cluster database
	// (POST /clusters/{cluster_uuid}/{database}/sql)
	ExecuteClusterSql(c fiber.Ctx, clusterUuid uuid.UUID, database string) error
	// List relation metadata for a cluster database
	// (GET /clusters/{cluster_uuid}/{database}/relations)
	ListClusterRelations(c fiber.Ctx, clusterUuid uuid.UUID, database string) error
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

type MiddlewareFunc fiber.Handler

// ListNotebooks operation middleware
func (siw *ServerInterfaceWrapper) ListNotebooks(c fiber.Ctx) error {
	return siw.Handler.ListNotebooks(c)
}

// CreateNotebook operation middleware
func (siw *ServerInterfaceWrapper) CreateNotebook(c fiber.Ctx) error {
	return siw.Handler.CreateNotebook(c)
}

// ConnectCluster operation middleware
func (siw *ServerInterfaceWrapper) ConnectCluster(c fiber.Ctx) error {
	return siw.Handler.ConnectCluster(c)
}

// ListClusterBackgroundProgress operation middleware
func (siw *ServerInterfaceWrapper) ListClusterBackgroundProgress(c fiber.Ctx) error {
	return siw.Handler.ListClusterBackgroundProgress(c)
}

// ListClusters operation middleware
func (siw *ServerInterfaceWrapper) ListClusters(c fiber.Ctx) error {
	return siw.Handler.ListClusters(c)
}

// ListBackgroundDdls operation middleware
func (siw *ServerInterfaceWrapper) ListBackgroundDdls(c fiber.Ctx) error {
	return siw.Handler.ListBackgroundDdls(c)
}

// CreateBackgroundDdl operation middleware
func (siw *ServerInterfaceWrapper) CreateBackgroundDdl(c fiber.Ctx) error {
	return siw.Handler.CreateBackgroundDdl(c)
}

// ReorderNotebookCells operation middleware
func (siw *ServerInterfaceWrapper) ReorderNotebookCells(c fiber.Ctx) error {
	var notebookUuid uuid.UUID
	notebookUuidValue := c.Params("notebook_uuid")
	parsedNotebookUuid, err := uuid.Parse(notebookUuidValue)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter notebook_uuid: %w", err).Error())
	}
	notebookUuid = parsedNotebookUuid

	return siw.Handler.ReorderNotebookCells(c, notebookUuid)
}

// CreateNotebookCell operation middleware
func (siw *ServerInterfaceWrapper) CreateNotebookCell(c fiber.Ctx) error {
	var notebookUuid uuid.UUID
	notebookUuidValue := c.Params("notebook_uuid")
	parsedNotebookUuid, err := uuid.Parse(notebookUuidValue)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter notebook_uuid: %w", err).Error())
	}
	notebookUuid = parsedNotebookUuid

	return siw.Handler.CreateNotebookCell(c, notebookUuid)
}

// GetNotebook operation middleware
func (siw *ServerInterfaceWrapper) GetNotebook(c fiber.Ctx) error {
	var notebookUuid uuid.UUID
	notebookUuidValue := c.Params("notebook_uuid")
	parsedNotebookUuid, err := uuid.Parse(notebookUuidValue)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter notebook_uuid: %w", err).Error())
	}
	notebookUuid = parsedNotebookUuid

	return siw.Handler.GetNotebook(c, notebookUuid)
}

// DeleteNotebook operation middleware
func (siw *ServerInterfaceWrapper) DeleteNotebook(c fiber.Ctx) error {
	var notebookUuid uuid.UUID
	notebookUuidValue := c.Params("notebook_uuid")
	parsedNotebookUuid, err := uuid.Parse(notebookUuidValue)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter notebook_uuid: %w", err).Error())
	}
	notebookUuid = parsedNotebookUuid

	return siw.Handler.DeleteNotebook(c, notebookUuid)
}

// ListClusterDatabases operation middleware
func (siw *ServerInterfaceWrapper) ListClusterDatabases(c fiber.Ctx) error {
	var clusterUuid uuid.UUID
	clusterUuidValue := c.Params("cluster_uuid")
	parsedClusterUuid, err := uuid.Parse(clusterUuidValue)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter cluster_uuid: %w", err).Error())
	}
	clusterUuid = parsedClusterUuid

	return siw.Handler.ListClusterDatabases(c, clusterUuid)
}

// UpdateCluster operation middleware
func (siw *ServerInterfaceWrapper) UpdateCluster(c fiber.Ctx) error {
	var clusterUuid uuid.UUID
	clusterUuidValue := c.Params("cluster_uuid")
	parsedClusterUuid, err := uuid.Parse(clusterUuidValue)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter cluster_uuid: %w", err).Error())
	}
	clusterUuid = parsedClusterUuid

	return siw.Handler.UpdateCluster(c, clusterUuid)
}

// DeleteCluster operation middleware
func (siw *ServerInterfaceWrapper) DeleteCluster(c fiber.Ctx) error {
	var clusterUuid uuid.UUID
	clusterUuidValue := c.Params("cluster_uuid")
	parsedClusterUuid, err := uuid.Parse(clusterUuidValue)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter cluster_uuid: %w", err).Error())
	}
	clusterUuid = parsedClusterUuid

	return siw.Handler.DeleteCluster(c, clusterUuid)
}

// DeleteBackgroundDdl operation middleware
func (siw *ServerInterfaceWrapper) DeleteBackgroundDdl(c fiber.Ctx) error {
	var id uuid.UUID
	idValue := c.Params("id")
	parsedId, err := uuid.Parse(idValue)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}
	id = parsedId

	return siw.Handler.DeleteBackgroundDdl(c, id)
}

// UpdateNotebookCell operation middleware
func (siw *ServerInterfaceWrapper) UpdateNotebookCell(c fiber.Ctx) error {
	var notebookUuid uuid.UUID
	notebookUuidValue := c.Params("notebook_uuid")
	parsedNotebookUuid, err := uuid.Parse(notebookUuidValue)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter notebook_uuid: %w", err).Error())
	}
	notebookUuid = parsedNotebookUuid

	var cellUuid uuid.UUID
	cellUuidValue := c.Params("cell_uuid")
	parsedCellUuid, err := uuid.Parse(cellUuidValue)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter cell_uuid: %w", err).Error())
	}
	cellUuid = parsedCellUuid

	return siw.Handler.UpdateNotebookCell(c, notebookUuid, cellUuid)
}

// DeleteNotebookCell operation middleware
func (siw *ServerInterfaceWrapper) DeleteNotebookCell(c fiber.Ctx) error {
	var notebookUuid uuid.UUID
	notebookUuidValue := c.Params("notebook_uuid")
	parsedNotebookUuid, err := uuid.Parse(notebookUuidValue)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter notebook_uuid: %w", err).Error())
	}
	notebookUuid = parsedNotebookUuid

	var cellUuid uuid.UUID
	cellUuidValue := c.Params("cell_uuid")
	parsedCellUuid, err := uuid.Parse(cellUuidValue)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter cell_uuid: %w", err).Error())
	}
	cellUuid = parsedCellUuid

	return siw.Handler.DeleteNotebookCell(c, notebookUuid, cellUuid)
}

// ExecuteClusterSql operation middleware
func (siw *ServerInterfaceWrapper) ExecuteClusterSql(c fiber.Ctx) error {
	var clusterUuid uuid.UUID
	clusterUuidValue := c.Params("cluster_uuid")
	parsedClusterUuid, err := uuid.Parse(clusterUuidValue)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter cluster_uuid: %w", err).Error())
	}
	clusterUuid = parsedClusterUuid

	var database string
	database = c.Params("database")

	return siw.Handler.ExecuteClusterSql(c, clusterUuid, database)
}

// ListClusterRelations operation middleware
func (siw *ServerInterfaceWrapper) ListClusterRelations(c fiber.Ctx) error {
	var clusterUuid uuid.UUID
	clusterUuidValue := c.Params("cluster_uuid")
	parsedClusterUuid, err := uuid.Parse(clusterUuidValue)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter cluster_uuid: %w", err).Error())
	}
	clusterUuid = parsedClusterUuid

	var database string
	database = c.Params("database")

	return siw.Handler.ListClusterRelations(c, clusterUuid, database)
}

// FiberServerOptions provides options for the Fiber server.
type FiberServerOptions struct {
	BaseURL     string
	Middlewares []MiddlewareFunc
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router fiber.Router, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, FiberServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router fiber.Router, si ServerInterface, options FiberServerOptions) {
	wrapper := ServerInterfaceWrapper{Handler: si}

	for _, m := range options.Middlewares {
		router.Use(fiber.Handler(m))
	}

	router.Get(options.BaseURL+"/notebooks", wrapper.ListNotebooks)

	router.Post(options.BaseURL+"/notebooks", wrapper.CreateNotebook)

	router.Post(options.BaseURL+"/clusters/connect", wrapper.ConnectCluster)

	router.Get(options.BaseURL+"/clusters/background-progress", wrapper.ListClusterBackgroundProgress)

	router.Get(options.BaseURL+"/clusters", wrapper.ListClusters)

	router.Get(options.BaseURL+"/background-ddls", wrapper.ListBackgroundDdls)

	router.Post(options.BaseURL+"/background-ddls", wrapper.CreateBackgroundDdl)

	router.Post(options.BaseURL+"/notebooks/:notebook_uuid/cells/order", wrapper.ReorderNotebookCells)

	router.Post(options.BaseURL+"/notebooks/:notebook_uuid/cells", wrapper.CreateNotebookCell)

	router.Get(options.BaseURL+"/notebooks/:notebook_uuid", wrapper.GetNotebook)

	router.Delete(options.BaseURL+"/notebooks/:notebook_uuid", wrapper.DeleteNotebook)

	router.Get(options.BaseURL+"/clusters/:cluster_uuid/databases", wrapper.ListClusterDatabases)

	router.Put(options.BaseURL+"/clusters/:cluster_uuid", wrapper.UpdateCluster)

	router.Delete(options.BaseURL+"/clusters/:cluster_uuid", wrapper.DeleteCluster)

	router.Delete(options.BaseURL+"/background-ddls/:id", wrapper.DeleteBackgroundDdl)

	router.Put(options.BaseURL+"/notebooks/:notebook_uuid/cells/:cell_uuid", wrapper.UpdateNotebookCell)

	router.Delete(options.BaseURL+"/notebooks/:notebook_uuid/cells/:cell_uuid", wrapper.DeleteNotebookCell)

	router.Post(options.BaseURL+"/clusters/:cluster_uuid/:database/sql", wrapper.ExecuteClusterSql)

	router.Get(options.BaseURL+"/clusters/:cluster_uuid/:database/relations", wrapper.ListClusterRelations)

}

type Validator interface {
	// AuthFunc is called before the request is processed. The response will be 401 if the auth fails.
	AuthFunc(fiber.Ctx) error

	// PreValidate is called before the request is processed. The response will be 403 if the validation fails.
	PreValidate(fiber.Ctx) error

	// PostValidate is called after the request is processed. The response will be 403 if the validation fails.
	PostValidate(fiber.Ctx) error
}

type XMiddleware struct {
	ServerInterface
	Validator
}

func NewXMiddleware(handler ServerInterface, validator Validator) ServerInterface {
	return &XMiddleware{ServerInterface: handler, Validator: validator}
}
