// Code generated by github.com/cloudcarver/anclax DO NOT EDIT.
package background_ddl

import "github.com/google/uuid"

type BackgroundDDLWatcherParameters struct {
	BackgroundDdlJobId uuid.UUID `json:"backgroundDdlJobId" yaml:"backgroundDdlJobId"`
}
