// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/cloudcarver/waitkit/app"
	"github.com/cloudcarver/waitkit/pkg/config"
	"github.com/cloudcarver/waitkit/pkg/handler"
	"github.com/cloudcarver/waitkit/pkg/model"
	"github.com/cloudcarver/waitkit/pkg/risingwave"
	"github.com/cloudcarver/waitkit/pkg/service"
)

// Injectors from wire.go:

func InitApp() (*app.App, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	application, err := app.InitAnclaxApplication(configConfig)
	if err != nil {
		return nil, err
	}
	modelInterface, err := model.NewModel(configConfig, application)
	if err != nil {
		return nil, err
	}
	client := risingwave.NewClient()
	serviceInterface := service.NewService(modelInterface, client)
	serverInterface, err := handler.NewHandler(serviceInterface)
	if err != nil {
		return nil, err
	}
	authInterface := app.InjectAuth(application)
	validator := handler.NewValidator(authInterface)
	plugin := app.NewPlugin(serverInterface, validator)
	appApp, err := app.Init(application, plugin)
	if err != nil {
		return nil, err
	}
	return appApp, nil
}
