// This file is generated by tools, DO NOT EDIT.
package taskgen

import (
	"context"
	"encoding/json"
	"fmt"
	"time"

	"github.com/cloudcarver/waitkit/pkg/zgen/schemas/background_ddl"

	"github.com/cloudcarver/waitkit/pkg/zgen/schemas/counter"

	"github.com/cloudcarver/anclax/core"
	"github.com/cloudcarver/anclax/pkg/zgen/apigen"
	taskcore "github.com/cloudcarver/anclax/pkg/taskcore/store"
	"github.com/cloudcarver/anclax/pkg/taskcore/worker"
	"github.com/cloudcarver/anclax/pkg/utils"
	"github.com/pkg/errors"
)

func init() {
	utils.Noop()
}

const ( 
	AutoIncrementCounter = "AutoIncrementCounter" 

	IncrementCounter = "IncrementCounter" 

	BackgroundDDLWatcher = "BackgroundDDLWatcher" 
)



type TaskRunner interface { 
    // Increment the counter
	RunAutoIncrementCounter(ctx context.Context, params *counter.IncrementCounterParams, overrides ...taskcore.TaskOverride) (int32, error)
    // Increment the counter
	RunAutoIncrementCounterWithTx(ctx context.Context, tx core.Tx, params *counter.IncrementCounterParams, overrides ...taskcore.TaskOverride) (int32, error)

    // Increment the counter
	RunIncrementCounter(ctx context.Context, params *counter.IncrementCounterParams, overrides ...taskcore.TaskOverride) (int32, error)
    // Increment the counter
	RunIncrementCounterWithTx(ctx context.Context, tx core.Tx, params *counter.IncrementCounterParams, overrides ...taskcore.TaskOverride) (int32, error)

    // Watch and advance a background DDL job
	RunBackgroundDDLWatcher(ctx context.Context, params *background_ddl.BackgroundDDLWatcherParameters, overrides ...taskcore.TaskOverride) (int32, error)
    // Watch and advance a background DDL job
	RunBackgroundDDLWatcherWithTx(ctx context.Context, tx core.Tx, params *background_ddl.BackgroundDDLWatcherParameters, overrides ...taskcore.TaskOverride) (int32, error)
}

type Client struct {
	taskStore taskcore.TaskStoreInterface
	now       func() time.Time
}

func NewTaskRunner(taskStore taskcore.TaskStoreInterface) TaskRunner {
	return &Client{
		taskStore: taskStore,
		now:       time.Now,
	}
}


func (c *Client) RunAutoIncrementCounter(ctx context.Context, params *counter.IncrementCounterParams, overrides ...taskcore.TaskOverride) (int32, error) {
	return c.runAutoIncrementCounter(ctx, c.taskStore, nil, params, overrides...)
}

func (c *Client) RunAutoIncrementCounterWithTx(ctx context.Context, tx core.Tx, params *counter.IncrementCounterParams, overrides ...taskcore.TaskOverride) (int32, error) {
	return c.runAutoIncrementCounter(ctx, c.taskStore, tx, params, overrides...)
}

func (c *Client) runAutoIncrementCounter(ctx context.Context, taskstore taskcore.TaskStoreInterface, tx core.Tx, params *counter.IncrementCounterParams, overrides ...taskcore.TaskOverride) (int32, error) {
	payload, err := json.Marshal(params)
	if err != nil {
		return 0, err
	}

	spec := apigen.TaskSpec{
		Type:    AutoIncrementCounter,
		Payload: payload,
	}
	attributes := apigen.TaskAttributes{}
	
	attributes.RetryPolicy = &apigen.TaskRetryPolicy{
		Interval:    "30m",
		MaxAttempts: -1,
	}
	attributes.Cronjob = &apigen.TaskCronjob{
		CronExpression: "*/5 * * * * *",
	}
	
	
	task := &apigen.Task{
		Attributes: attributes,
		Spec:       spec,
		Status:     apigen.Pending,
	}
	
	for _, override := range overrides {
		if err := override(task); err != nil {
			return 0, errors.Wrap(err, "failed to apply task override")
		}
	}
	var taskID int32
	if tx == nil {
		taskID, err = taskstore.PushTask(ctx, task)
	} else {
		taskID, err = taskstore.PushTaskWithTx(ctx, tx, task)
	}
	if err != nil {
		return 0, err
	}
	return taskID, nil
}
func (c *Client) RunIncrementCounter(ctx context.Context, params *counter.IncrementCounterParams, overrides ...taskcore.TaskOverride) (int32, error) {
	return c.runIncrementCounter(ctx, c.taskStore, nil, params, overrides...)
}

func (c *Client) RunIncrementCounterWithTx(ctx context.Context, tx core.Tx, params *counter.IncrementCounterParams, overrides ...taskcore.TaskOverride) (int32, error) {
	return c.runIncrementCounter(ctx, c.taskStore, tx, params, overrides...)
}

func (c *Client) runIncrementCounter(ctx context.Context, taskstore taskcore.TaskStoreInterface, tx core.Tx, params *counter.IncrementCounterParams, overrides ...taskcore.TaskOverride) (int32, error) {
	payload, err := json.Marshal(params)
	if err != nil {
		return 0, err
	}

	spec := apigen.TaskSpec{
		Type:    IncrementCounter,
		Payload: payload,
	}
	attributes := apigen.TaskAttributes{}
	
	attributes.RetryPolicy = &apigen.TaskRetryPolicy{
		Interval:    "30m",
		MaxAttempts: -1,
	}
	
	
	
	task := &apigen.Task{
		Attributes: attributes,
		Spec:       spec,
		Status:     apigen.Pending,
	}
	
	for _, override := range overrides {
		if err := override(task); err != nil {
			return 0, errors.Wrap(err, "failed to apply task override")
		}
	}
	var taskID int32
	if tx == nil {
		taskID, err = taskstore.PushTask(ctx, task)
	} else {
		taskID, err = taskstore.PushTaskWithTx(ctx, tx, task)
	}
	if err != nil {
		return 0, err
	}
	return taskID, nil
}
func (c *Client) RunBackgroundDDLWatcher(ctx context.Context, params *background_ddl.BackgroundDDLWatcherParameters, overrides ...taskcore.TaskOverride) (int32, error) {
	return c.runBackgroundDDLWatcher(ctx, c.taskStore, nil, params, overrides...)
}

func (c *Client) RunBackgroundDDLWatcherWithTx(ctx context.Context, tx core.Tx, params *background_ddl.BackgroundDDLWatcherParameters, overrides ...taskcore.TaskOverride) (int32, error) {
	return c.runBackgroundDDLWatcher(ctx, c.taskStore, tx, params, overrides...)
}

func (c *Client) runBackgroundDDLWatcher(ctx context.Context, taskstore taskcore.TaskStoreInterface, tx core.Tx, params *background_ddl.BackgroundDDLWatcherParameters, overrides ...taskcore.TaskOverride) (int32, error) {
	payload, err := json.Marshal(params)
	if err != nil {
		return 0, err
	}

	spec := apigen.TaskSpec{
		Type:    BackgroundDDLWatcher,
		Payload: payload,
	}
	attributes := apigen.TaskAttributes{}
	
	attributes.RetryPolicy = &apigen.TaskRetryPolicy{
		Interval:    "5s",
		MaxAttempts: -1,
	}
	
	
	
	task := &apigen.Task{
		Attributes: attributes,
		Spec:       spec,
		Status:     apigen.Pending,
	}
	
	for _, override := range overrides {
		if err := override(task); err != nil {
			return 0, errors.Wrap(err, "failed to apply task override")
		}
	}
	var taskID int32
	if tx == nil {
		taskID, err = taskstore.PushTask(ctx, task)
	} else {
		taskID, err = taskstore.PushTaskWithTx(ctx, tx, task)
	}
	if err != nil {
		return 0, err
	}
	return taskID, nil
}



type ExecutorInterface interface { 
     // Increment the counter
	ExecuteAutoIncrementCounter(ctx context.Context, task worker.Task, params *counter.IncrementCounterParams) error
 

     // Increment the counter
	ExecuteIncrementCounter(ctx context.Context, task worker.Task, params *counter.IncrementCounterParams) error
 

     // Watch and advance a background DDL job
	ExecuteBackgroundDDLWatcher(ctx context.Context, task worker.Task, params *background_ddl.BackgroundDDLWatcherParameters) error
 
	// Hook called when BackgroundDDLWatcher fails
	OnBackgroundDDLWatcherFailed(ctx context.Context, taskID int32, params *background_ddl.BackgroundDDLWatcherParameters, tx core.Tx) error
}

type TaskHandler struct {
	executor ExecutorInterface

	externalTaskHandler []worker.TaskHandler
}

func NewTaskHandler(executor ExecutorInterface) worker.TaskHandler {
	return &TaskHandler{
		executor: executor,
	}
}

func (f *TaskHandler) RegisterTaskHandler(handler worker.TaskHandler) {
	f.externalTaskHandler = append(f.externalTaskHandler, handler)
}

func (f *TaskHandler) HandleTask(ctx context.Context, task worker.Task) error {
	for _, handler := range f.externalTaskHandler {
		if err := handler.HandleTask(ctx, task); err != nil {
			if errors.Is(err, worker.ErrUnknownTaskType) {
				continue
			}
			return err
		}
		return nil
	}

	switch task.GetType() { 
	case AutoIncrementCounter:
		var params counter.IncrementCounterParams
		if err := json.Unmarshal(task.GetPayload(), &params); err != nil {
			return fmt.Errorf("failed to parse AutoIncrementCounter parameters: %w", err)
		}
		return f.executor.ExecuteAutoIncrementCounter(ctx, task, &params)
		
	case IncrementCounter:
		var params counter.IncrementCounterParams
		if err := json.Unmarshal(task.GetPayload(), &params); err != nil {
			return fmt.Errorf("failed to parse IncrementCounter parameters: %w", err)
		}
		return f.executor.ExecuteIncrementCounter(ctx, task, &params)
		
	case BackgroundDDLWatcher:
		var params background_ddl.BackgroundDDLWatcherParameters
		if err := json.Unmarshal(task.GetPayload(), &params); err != nil {
			return fmt.Errorf("failed to parse BackgroundDDLWatcher parameters: %w", err)
		}
		return f.executor.ExecuteBackgroundDDLWatcher(ctx, task, &params)
		
	default:
		return errors.Wrapf(worker.ErrUnknownTaskType, "unknown task type: %s", task.GetType())
	}
}

func (f *TaskHandler) OnTaskFailed(ctx context.Context, tx core.Tx, failedTaskSpec worker.TaskSpec, taskID int32) error {
	for _, handler := range f.externalTaskHandler {
		if err := handler.OnTaskFailed(ctx, tx, failedTaskSpec, taskID); err != nil {
			if errors.Is(err, worker.ErrUnknownTaskType) {
				continue
			}
			return err
		}
		return nil
	}

	// Call the appropriate OnXXXFailed hook method
	switch failedTaskSpec.GetType() { 
	case BackgroundDDLWatcher:
		var params background_ddl.BackgroundDDLWatcherParameters
		if err := json.Unmarshal(failedTaskSpec.GetPayload(), &params); err != nil {
			return fmt.Errorf("failed to parse BackgroundDDLWatcher parameters: %w", err)
		}
		return f.executor.OnBackgroundDDLWatcherFailed(ctx, taskID, &params, tx)
	default:
		return nil // No hook configured for this task type
	}
}
