// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/model/model.go
//
// Generated by this command:
//
//	mockgen -source pkg/model/model.go -destination pkg/model/mock_gen.go -package model
//

// Package model is a generated GoMock package.
package model

import (
	context "context"
	reflect "reflect"

	querier "github.com/cloudcarver/waitkit/pkg/zgen/querier"
	uuid "github.com/google/uuid"
	pgx "github.com/jackc/pgx/v5"
	gomock "go.uber.org/mock/gomock"
)

// MockModelInterface is a mock of ModelInterface interface.
type MockModelInterface struct {
	ctrl     *gomock.Controller
	recorder *MockModelInterfaceMockRecorder
	isgomock struct{}
}

// MockModelInterfaceMockRecorder is the mock recorder for MockModelInterface.
type MockModelInterfaceMockRecorder struct {
	mock *MockModelInterface
}

// NewMockModelInterface creates a new mock instance.
func NewMockModelInterface(ctrl *gomock.Controller) *MockModelInterface {
	mock := &MockModelInterface{ctrl: ctrl}
	mock.recorder = &MockModelInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockModelInterface) EXPECT() *MockModelInterfaceMockRecorder {
	return m.recorder
}

// CancelPendingBackgroundDdlProgresses mocks base method.
func (m *MockModelInterface) CancelPendingBackgroundDdlProgresses(ctx context.Context, jobID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelPendingBackgroundDdlProgresses", ctx, jobID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelPendingBackgroundDdlProgresses indicates an expected call of CancelPendingBackgroundDdlProgresses.
func (mr *MockModelInterfaceMockRecorder) CancelPendingBackgroundDdlProgresses(ctx, jobID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelPendingBackgroundDdlProgresses", reflect.TypeOf((*MockModelInterface)(nil).CancelPendingBackgroundDdlProgresses), ctx, jobID)
}

// Close mocks base method.
func (m *MockModelInterface) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockModelInterfaceMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockModelInterface)(nil).Close))
}

// CreateBackgroundDdlJob mocks base method.
func (m *MockModelInterface) CreateBackgroundDdlJob(ctx context.Context, arg querier.CreateBackgroundDdlJobParams) (*querier.BackgroundDdlJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBackgroundDdlJob", ctx, arg)
	ret0, _ := ret[0].(*querier.BackgroundDdlJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBackgroundDdlJob indicates an expected call of CreateBackgroundDdlJob.
func (mr *MockModelInterfaceMockRecorder) CreateBackgroundDdlJob(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBackgroundDdlJob", reflect.TypeOf((*MockModelInterface)(nil).CreateBackgroundDdlJob), ctx, arg)
}

// CreateBackgroundDdlProgress mocks base method.
func (m *MockModelInterface) CreateBackgroundDdlProgress(ctx context.Context, arg querier.CreateBackgroundDdlProgressParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBackgroundDdlProgress", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBackgroundDdlProgress indicates an expected call of CreateBackgroundDdlProgress.
func (mr *MockModelInterfaceMockRecorder) CreateBackgroundDdlProgress(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBackgroundDdlProgress", reflect.TypeOf((*MockModelInterface)(nil).CreateBackgroundDdlProgress), ctx, arg)
}

// CreateCluster mocks base method.
func (m *MockModelInterface) CreateCluster(ctx context.Context, arg querier.CreateClusterParams) (*querier.Cluster, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCluster", ctx, arg)
	ret0, _ := ret[0].(*querier.Cluster)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCluster indicates an expected call of CreateCluster.
func (mr *MockModelInterfaceMockRecorder) CreateCluster(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCluster", reflect.TypeOf((*MockModelInterface)(nil).CreateCluster), ctx, arg)
}

// CreateNotebook mocks base method.
func (m *MockModelInterface) CreateNotebook(ctx context.Context, notebookName string) (*querier.Notebook, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNotebook", ctx, notebookName)
	ret0, _ := ret[0].(*querier.Notebook)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateNotebook indicates an expected call of CreateNotebook.
func (mr *MockModelInterfaceMockRecorder) CreateNotebook(ctx, notebookName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNotebook", reflect.TypeOf((*MockModelInterface)(nil).CreateNotebook), ctx, notebookName)
}

// CreateNotebookCell mocks base method.
func (m *MockModelInterface) CreateNotebookCell(ctx context.Context, arg querier.CreateNotebookCellParams) (*querier.NotebookCell, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNotebookCell", ctx, arg)
	ret0, _ := ret[0].(*querier.NotebookCell)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateNotebookCell indicates an expected call of CreateNotebookCell.
func (mr *MockModelInterfaceMockRecorder) CreateNotebookCell(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNotebookCell", reflect.TypeOf((*MockModelInterface)(nil).CreateNotebookCell), ctx, arg)
}

// DeleteCluster mocks base method.
func (m *MockModelInterface) DeleteCluster(ctx context.Context, clusterUuid uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCluster", ctx, clusterUuid)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCluster indicates an expected call of DeleteCluster.
func (mr *MockModelInterfaceMockRecorder) DeleteCluster(ctx, clusterUuid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCluster", reflect.TypeOf((*MockModelInterface)(nil).DeleteCluster), ctx, clusterUuid)
}

// DeleteNotebook mocks base method.
func (m *MockModelInterface) DeleteNotebook(ctx context.Context, notebookUuid uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNotebook", ctx, notebookUuid)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteNotebook indicates an expected call of DeleteNotebook.
func (mr *MockModelInterfaceMockRecorder) DeleteNotebook(ctx, notebookUuid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNotebook", reflect.TypeOf((*MockModelInterface)(nil).DeleteNotebook), ctx, notebookUuid)
}

// DeleteNotebookCell mocks base method.
func (m *MockModelInterface) DeleteNotebookCell(ctx context.Context, arg querier.DeleteNotebookCellParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNotebookCell", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteNotebookCell indicates an expected call of DeleteNotebookCell.
func (mr *MockModelInterfaceMockRecorder) DeleteNotebookCell(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNotebookCell", reflect.TypeOf((*MockModelInterface)(nil).DeleteNotebookCell), ctx, arg)
}

// GetBackgroundDdlJob mocks base method.
func (m *MockModelInterface) GetBackgroundDdlJob(ctx context.Context, id uuid.UUID) (*querier.BackgroundDdlJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBackgroundDdlJob", ctx, id)
	ret0, _ := ret[0].(*querier.BackgroundDdlJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBackgroundDdlJob indicates an expected call of GetBackgroundDdlJob.
func (mr *MockModelInterfaceMockRecorder) GetBackgroundDdlJob(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBackgroundDdlJob", reflect.TypeOf((*MockModelInterface)(nil).GetBackgroundDdlJob), ctx, id)
}

// GetCluster mocks base method.
func (m *MockModelInterface) GetCluster(ctx context.Context, clusterUuid uuid.UUID) (*querier.Cluster, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCluster", ctx, clusterUuid)
	ret0, _ := ret[0].(*querier.Cluster)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCluster indicates an expected call of GetCluster.
func (mr *MockModelInterfaceMockRecorder) GetCluster(ctx, clusterUuid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCluster", reflect.TypeOf((*MockModelInterface)(nil).GetCluster), ctx, clusterUuid)
}

// GetCounter mocks base method.
func (m *MockModelInterface) GetCounter(ctx context.Context) (*querier.Counter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCounter", ctx)
	ret0, _ := ret[0].(*querier.Counter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCounter indicates an expected call of GetCounter.
func (mr *MockModelInterfaceMockRecorder) GetCounter(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCounter", reflect.TypeOf((*MockModelInterface)(nil).GetCounter), ctx)
}

// GetNextBackgroundDdlProgress mocks base method.
func (m *MockModelInterface) GetNextBackgroundDdlProgress(ctx context.Context, jobID uuid.UUID) (*querier.BackgroundDdlProgress, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNextBackgroundDdlProgress", ctx, jobID)
	ret0, _ := ret[0].(*querier.BackgroundDdlProgress)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNextBackgroundDdlProgress indicates an expected call of GetNextBackgroundDdlProgress.
func (mr *MockModelInterfaceMockRecorder) GetNextBackgroundDdlProgress(ctx, jobID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNextBackgroundDdlProgress", reflect.TypeOf((*MockModelInterface)(nil).GetNextBackgroundDdlProgress), ctx, jobID)
}

// GetNextNotebookCellOrder mocks base method.
func (m *MockModelInterface) GetNextNotebookCellOrder(ctx context.Context, notebookUuid uuid.UUID) (int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNextNotebookCellOrder", ctx, notebookUuid)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNextNotebookCellOrder indicates an expected call of GetNextNotebookCellOrder.
func (mr *MockModelInterfaceMockRecorder) GetNextNotebookCellOrder(ctx, notebookUuid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNextNotebookCellOrder", reflect.TypeOf((*MockModelInterface)(nil).GetNextNotebookCellOrder), ctx, notebookUuid)
}

// GetNotebook mocks base method.
func (m *MockModelInterface) GetNotebook(ctx context.Context, notebookUuid uuid.UUID) (*querier.Notebook, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNotebook", ctx, notebookUuid)
	ret0, _ := ret[0].(*querier.Notebook)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNotebook indicates an expected call of GetNotebook.
func (mr *MockModelInterfaceMockRecorder) GetNotebook(ctx, notebookUuid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNotebook", reflect.TypeOf((*MockModelInterface)(nil).GetNotebook), ctx, notebookUuid)
}

// GetNotebookCell mocks base method.
func (m *MockModelInterface) GetNotebookCell(ctx context.Context, arg querier.GetNotebookCellParams) (*querier.NotebookCell, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNotebookCell", ctx, arg)
	ret0, _ := ret[0].(*querier.NotebookCell)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNotebookCell indicates an expected call of GetNotebookCell.
func (mr *MockModelInterfaceMockRecorder) GetNotebookCell(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNotebookCell", reflect.TypeOf((*MockModelInterface)(nil).GetNotebookCell), ctx, arg)
}

// InTransaction mocks base method.
func (m *MockModelInterface) InTransaction() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InTransaction")
	ret0, _ := ret[0].(bool)
	return ret0
}

// InTransaction indicates an expected call of InTransaction.
func (mr *MockModelInterfaceMockRecorder) InTransaction() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InTransaction", reflect.TypeOf((*MockModelInterface)(nil).InTransaction))
}

// IncrementCounter mocks base method.
func (m *MockModelInterface) IncrementCounter(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementCounter", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementCounter indicates an expected call of IncrementCounter.
func (mr *MockModelInterfaceMockRecorder) IncrementCounter(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementCounter", reflect.TypeOf((*MockModelInterface)(nil).IncrementCounter), ctx)
}

// ListBackgroundDdlJobs mocks base method.
func (m *MockModelInterface) ListBackgroundDdlJobs(ctx context.Context) ([]*querier.BackgroundDdlJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBackgroundDdlJobs", ctx)
	ret0, _ := ret[0].([]*querier.BackgroundDdlJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBackgroundDdlJobs indicates an expected call of ListBackgroundDdlJobs.
func (mr *MockModelInterfaceMockRecorder) ListBackgroundDdlJobs(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBackgroundDdlJobs", reflect.TypeOf((*MockModelInterface)(nil).ListBackgroundDdlJobs), ctx)
}

// ListBackgroundDdlProgresses mocks base method.
func (m *MockModelInterface) ListBackgroundDdlProgresses(ctx context.Context) ([]*querier.BackgroundDdlProgress, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBackgroundDdlProgresses", ctx)
	ret0, _ := ret[0].([]*querier.BackgroundDdlProgress)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBackgroundDdlProgresses indicates an expected call of ListBackgroundDdlProgresses.
func (mr *MockModelInterfaceMockRecorder) ListBackgroundDdlProgresses(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBackgroundDdlProgresses", reflect.TypeOf((*MockModelInterface)(nil).ListBackgroundDdlProgresses), ctx)
}

// ListBackgroundDdlProgressesByJob mocks base method.
func (m *MockModelInterface) ListBackgroundDdlProgressesByJob(ctx context.Context, jobID uuid.UUID) ([]*querier.BackgroundDdlProgress, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBackgroundDdlProgressesByJob", ctx, jobID)
	ret0, _ := ret[0].([]*querier.BackgroundDdlProgress)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBackgroundDdlProgressesByJob indicates an expected call of ListBackgroundDdlProgressesByJob.
func (mr *MockModelInterfaceMockRecorder) ListBackgroundDdlProgressesByJob(ctx, jobID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBackgroundDdlProgressesByJob", reflect.TypeOf((*MockModelInterface)(nil).ListBackgroundDdlProgressesByJob), ctx, jobID)
}

// ListClusters mocks base method.
func (m *MockModelInterface) ListClusters(ctx context.Context) ([]*querier.Cluster, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListClusters", ctx)
	ret0, _ := ret[0].([]*querier.Cluster)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListClusters indicates an expected call of ListClusters.
func (mr *MockModelInterfaceMockRecorder) ListClusters(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListClusters", reflect.TypeOf((*MockModelInterface)(nil).ListClusters), ctx)
}

// ListNotebookCells mocks base method.
func (m *MockModelInterface) ListNotebookCells(ctx context.Context, notebookUuid uuid.UUID) ([]*querier.NotebookCell, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListNotebookCells", ctx, notebookUuid)
	ret0, _ := ret[0].([]*querier.NotebookCell)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListNotebookCells indicates an expected call of ListNotebookCells.
func (mr *MockModelInterfaceMockRecorder) ListNotebookCells(ctx, notebookUuid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListNotebookCells", reflect.TypeOf((*MockModelInterface)(nil).ListNotebookCells), ctx, notebookUuid)
}

// ListNotebooks mocks base method.
func (m *MockModelInterface) ListNotebooks(ctx context.Context) ([]*querier.Notebook, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListNotebooks", ctx)
	ret0, _ := ret[0].([]*querier.Notebook)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListNotebooks indicates an expected call of ListNotebooks.
func (mr *MockModelInterfaceMockRecorder) ListNotebooks(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListNotebooks", reflect.TypeOf((*MockModelInterface)(nil).ListNotebooks), ctx)
}

// MarkBackgroundDdlJobCancelRequested mocks base method.
func (m *MockModelInterface) MarkBackgroundDdlJobCancelRequested(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkBackgroundDdlJobCancelRequested", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkBackgroundDdlJobCancelRequested indicates an expected call of MarkBackgroundDdlJobCancelRequested.
func (mr *MockModelInterfaceMockRecorder) MarkBackgroundDdlJobCancelRequested(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkBackgroundDdlJobCancelRequested", reflect.TypeOf((*MockModelInterface)(nil).MarkBackgroundDdlJobCancelRequested), ctx, id)
}

// MarkBackgroundDdlJobCancelled mocks base method.
func (m *MockModelInterface) MarkBackgroundDdlJobCancelled(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkBackgroundDdlJobCancelled", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkBackgroundDdlJobCancelled indicates an expected call of MarkBackgroundDdlJobCancelled.
func (mr *MockModelInterfaceMockRecorder) MarkBackgroundDdlJobCancelled(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkBackgroundDdlJobCancelled", reflect.TypeOf((*MockModelInterface)(nil).MarkBackgroundDdlJobCancelled), ctx, id)
}

// MarkBackgroundDdlJobFailed mocks base method.
func (m *MockModelInterface) MarkBackgroundDdlJobFailed(ctx context.Context, arg querier.MarkBackgroundDdlJobFailedParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkBackgroundDdlJobFailed", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkBackgroundDdlJobFailed indicates an expected call of MarkBackgroundDdlJobFailed.
func (mr *MockModelInterfaceMockRecorder) MarkBackgroundDdlJobFailed(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkBackgroundDdlJobFailed", reflect.TypeOf((*MockModelInterface)(nil).MarkBackgroundDdlJobFailed), ctx, arg)
}

// MarkBackgroundDdlJobFinished mocks base method.
func (m *MockModelInterface) MarkBackgroundDdlJobFinished(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkBackgroundDdlJobFinished", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkBackgroundDdlJobFinished indicates an expected call of MarkBackgroundDdlJobFinished.
func (mr *MockModelInterfaceMockRecorder) MarkBackgroundDdlJobFinished(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkBackgroundDdlJobFinished", reflect.TypeOf((*MockModelInterface)(nil).MarkBackgroundDdlJobFinished), ctx, id)
}

// MarkBackgroundDdlJobStarted mocks base method.
func (m *MockModelInterface) MarkBackgroundDdlJobStarted(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkBackgroundDdlJobStarted", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkBackgroundDdlJobStarted indicates an expected call of MarkBackgroundDdlJobStarted.
func (mr *MockModelInterfaceMockRecorder) MarkBackgroundDdlJobStarted(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkBackgroundDdlJobStarted", reflect.TypeOf((*MockModelInterface)(nil).MarkBackgroundDdlJobStarted), ctx, id)
}

// MarkBackgroundDdlProgressCancelled mocks base method.
func (m *MockModelInterface) MarkBackgroundDdlProgressCancelled(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkBackgroundDdlProgressCancelled", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkBackgroundDdlProgressCancelled indicates an expected call of MarkBackgroundDdlProgressCancelled.
func (mr *MockModelInterfaceMockRecorder) MarkBackgroundDdlProgressCancelled(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkBackgroundDdlProgressCancelled", reflect.TypeOf((*MockModelInterface)(nil).MarkBackgroundDdlProgressCancelled), ctx, id)
}

// MarkBackgroundDdlProgressFailed mocks base method.
func (m *MockModelInterface) MarkBackgroundDdlProgressFailed(ctx context.Context, arg querier.MarkBackgroundDdlProgressFailedParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkBackgroundDdlProgressFailed", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkBackgroundDdlProgressFailed indicates an expected call of MarkBackgroundDdlProgressFailed.
func (mr *MockModelInterfaceMockRecorder) MarkBackgroundDdlProgressFailed(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkBackgroundDdlProgressFailed", reflect.TypeOf((*MockModelInterface)(nil).MarkBackgroundDdlProgressFailed), ctx, arg)
}

// MarkBackgroundDdlProgressFinished mocks base method.
func (m *MockModelInterface) MarkBackgroundDdlProgressFinished(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkBackgroundDdlProgressFinished", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkBackgroundDdlProgressFinished indicates an expected call of MarkBackgroundDdlProgressFinished.
func (mr *MockModelInterfaceMockRecorder) MarkBackgroundDdlProgressFinished(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkBackgroundDdlProgressFinished", reflect.TypeOf((*MockModelInterface)(nil).MarkBackgroundDdlProgressFinished), ctx, id)
}

// MarkBackgroundDdlProgressStarted mocks base method.
func (m *MockModelInterface) MarkBackgroundDdlProgressStarted(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkBackgroundDdlProgressStarted", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkBackgroundDdlProgressStarted indicates an expected call of MarkBackgroundDdlProgressStarted.
func (mr *MockModelInterfaceMockRecorder) MarkBackgroundDdlProgressStarted(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkBackgroundDdlProgressStarted", reflect.TypeOf((*MockModelInterface)(nil).MarkBackgroundDdlProgressStarted), ctx, id)
}

// RunTransaction mocks base method.
func (m *MockModelInterface) RunTransaction(ctx context.Context, f func(ModelInterface) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunTransaction", ctx, f)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunTransaction indicates an expected call of RunTransaction.
func (mr *MockModelInterfaceMockRecorder) RunTransaction(ctx, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunTransaction", reflect.TypeOf((*MockModelInterface)(nil).RunTransaction), ctx, f)
}

// RunTransactionWithTx mocks base method.
func (m *MockModelInterface) RunTransactionWithTx(ctx context.Context, f func(pgx.Tx, ModelInterface) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunTransactionWithTx", ctx, f)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunTransactionWithTx indicates an expected call of RunTransactionWithTx.
func (mr *MockModelInterfaceMockRecorder) RunTransactionWithTx(ctx, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunTransactionWithTx", reflect.TypeOf((*MockModelInterface)(nil).RunTransactionWithTx), ctx, f)
}

// SpawnWithTx mocks base method.
func (m *MockModelInterface) SpawnWithTx(tx pgx.Tx) ModelInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SpawnWithTx", tx)
	ret0, _ := ret[0].(ModelInterface)
	return ret0
}

// SpawnWithTx indicates an expected call of SpawnWithTx.
func (mr *MockModelInterfaceMockRecorder) SpawnWithTx(tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SpawnWithTx", reflect.TypeOf((*MockModelInterface)(nil).SpawnWithTx), tx)
}

// UpdateBackgroundDdlJobTaskID mocks base method.
func (m *MockModelInterface) UpdateBackgroundDdlJobTaskID(ctx context.Context, arg querier.UpdateBackgroundDdlJobTaskIDParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBackgroundDdlJobTaskID", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBackgroundDdlJobTaskID indicates an expected call of UpdateBackgroundDdlJobTaskID.
func (mr *MockModelInterfaceMockRecorder) UpdateBackgroundDdlJobTaskID(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBackgroundDdlJobTaskID", reflect.TypeOf((*MockModelInterface)(nil).UpdateBackgroundDdlJobTaskID), ctx, arg)
}

// UpdateBackgroundDdlProgressTracking mocks base method.
func (m *MockModelInterface) UpdateBackgroundDdlProgressTracking(ctx context.Context, arg querier.UpdateBackgroundDdlProgressTrackingParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBackgroundDdlProgressTracking", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBackgroundDdlProgressTracking indicates an expected call of UpdateBackgroundDdlProgressTracking.
func (mr *MockModelInterfaceMockRecorder) UpdateBackgroundDdlProgressTracking(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBackgroundDdlProgressTracking", reflect.TypeOf((*MockModelInterface)(nil).UpdateBackgroundDdlProgressTracking), ctx, arg)
}

// UpdateCluster mocks base method.
func (m *MockModelInterface) UpdateCluster(ctx context.Context, arg querier.UpdateClusterParams) (*querier.Cluster, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCluster", ctx, arg)
	ret0, _ := ret[0].(*querier.Cluster)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCluster indicates an expected call of UpdateCluster.
func (mr *MockModelInterfaceMockRecorder) UpdateCluster(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCluster", reflect.TypeOf((*MockModelInterface)(nil).UpdateCluster), ctx, arg)
}

// UpdateNotebookCell mocks base method.
func (m *MockModelInterface) UpdateNotebookCell(ctx context.Context, arg querier.UpdateNotebookCellParams) (*querier.NotebookCell, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateNotebookCell", ctx, arg)
	ret0, _ := ret[0].(*querier.NotebookCell)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateNotebookCell indicates an expected call of UpdateNotebookCell.
func (mr *MockModelInterfaceMockRecorder) UpdateNotebookCell(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNotebookCell", reflect.TypeOf((*MockModelInterface)(nil).UpdateNotebookCell), ctx, arg)
}

// UpdateNotebookCellOrder mocks base method.
func (m *MockModelInterface) UpdateNotebookCellOrder(ctx context.Context, arg querier.UpdateNotebookCellOrderParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateNotebookCellOrder", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateNotebookCellOrder indicates an expected call of UpdateNotebookCellOrder.
func (mr *MockModelInterfaceMockRecorder) UpdateNotebookCellOrder(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNotebookCellOrder", reflect.TypeOf((*MockModelInterface)(nil).UpdateNotebookCellOrder), ctx, arg)
}

// UpdateNotebookTimestamp mocks base method.
func (m *MockModelInterface) UpdateNotebookTimestamp(ctx context.Context, notebookUuid uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateNotebookTimestamp", ctx, notebookUuid)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateNotebookTimestamp indicates an expected call of UpdateNotebookTimestamp.
func (mr *MockModelInterfaceMockRecorder) UpdateNotebookTimestamp(ctx, notebookUuid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNotebookTimestamp", reflect.TypeOf((*MockModelInterface)(nil).UpdateNotebookTimestamp), ctx, notebookUuid)
}
