// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/model/model.go
//
// Generated by this command:
//
//	mockgen -source pkg/model/model.go -destination pkg/model/mock_gen.go -package model
//

// Package model is a generated GoMock package.
package model

import (
	context "context"
	reflect "reflect"

	querier "github.com/cloudcarver/waitkit/pkg/zgen/querier"
	uuid "github.com/google/uuid"
	pgx "github.com/jackc/pgx/v5"
	gomock "go.uber.org/mock/gomock"
)

// MockModelInterface is a mock of ModelInterface interface.
type MockModelInterface struct {
	ctrl     *gomock.Controller
	recorder *MockModelInterfaceMockRecorder
	isgomock struct{}
}

// MockModelInterfaceMockRecorder is the mock recorder for MockModelInterface.
type MockModelInterfaceMockRecorder struct {
	mock *MockModelInterface
}

// NewMockModelInterface creates a new mock instance.
func NewMockModelInterface(ctrl *gomock.Controller) *MockModelInterface {
	mock := &MockModelInterface{ctrl: ctrl}
	mock.recorder = &MockModelInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockModelInterface) EXPECT() *MockModelInterfaceMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockModelInterface) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockModelInterfaceMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockModelInterface)(nil).Close))
}

// CreateCluster mocks base method.
func (m *MockModelInterface) CreateCluster(ctx context.Context, arg querier.CreateClusterParams) (*querier.Cluster, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCluster", ctx, arg)
	ret0, _ := ret[0].(*querier.Cluster)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCluster indicates an expected call of CreateCluster.
func (mr *MockModelInterfaceMockRecorder) CreateCluster(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCluster", reflect.TypeOf((*MockModelInterface)(nil).CreateCluster), ctx, arg)
}

// CreateNotebook mocks base method.
func (m *MockModelInterface) CreateNotebook(ctx context.Context, notebookName string) (*querier.Notebook, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNotebook", ctx, notebookName)
	ret0, _ := ret[0].(*querier.Notebook)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateNotebook indicates an expected call of CreateNotebook.
func (mr *MockModelInterfaceMockRecorder) CreateNotebook(ctx, notebookName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNotebook", reflect.TypeOf((*MockModelInterface)(nil).CreateNotebook), ctx, notebookName)
}

// CreateNotebookCell mocks base method.
func (m *MockModelInterface) CreateNotebookCell(ctx context.Context, arg querier.CreateNotebookCellParams) (*querier.NotebookCell, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNotebookCell", ctx, arg)
	ret0, _ := ret[0].(*querier.NotebookCell)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateNotebookCell indicates an expected call of CreateNotebookCell.
func (mr *MockModelInterfaceMockRecorder) CreateNotebookCell(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNotebookCell", reflect.TypeOf((*MockModelInterface)(nil).CreateNotebookCell), ctx, arg)
}

// DeleteCluster mocks base method.
func (m *MockModelInterface) DeleteCluster(ctx context.Context, clusterUuid uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCluster", ctx, clusterUuid)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCluster indicates an expected call of DeleteCluster.
func (mr *MockModelInterfaceMockRecorder) DeleteCluster(ctx, clusterUuid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCluster", reflect.TypeOf((*MockModelInterface)(nil).DeleteCluster), ctx, clusterUuid)
}

// DeleteNotebook mocks base method.
func (m *MockModelInterface) DeleteNotebook(ctx context.Context, notebookUuid uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNotebook", ctx, notebookUuid)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteNotebook indicates an expected call of DeleteNotebook.
func (mr *MockModelInterfaceMockRecorder) DeleteNotebook(ctx, notebookUuid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNotebook", reflect.TypeOf((*MockModelInterface)(nil).DeleteNotebook), ctx, notebookUuid)
}

// DeleteNotebookCell mocks base method.
func (m *MockModelInterface) DeleteNotebookCell(ctx context.Context, arg querier.DeleteNotebookCellParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNotebookCell", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteNotebookCell indicates an expected call of DeleteNotebookCell.
func (mr *MockModelInterfaceMockRecorder) DeleteNotebookCell(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNotebookCell", reflect.TypeOf((*MockModelInterface)(nil).DeleteNotebookCell), ctx, arg)
}

// GetCluster mocks base method.
func (m *MockModelInterface) GetCluster(ctx context.Context, clusterUuid uuid.UUID) (*querier.Cluster, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCluster", ctx, clusterUuid)
	ret0, _ := ret[0].(*querier.Cluster)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCluster indicates an expected call of GetCluster.
func (mr *MockModelInterfaceMockRecorder) GetCluster(ctx, clusterUuid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCluster", reflect.TypeOf((*MockModelInterface)(nil).GetCluster), ctx, clusterUuid)
}

// GetCounter mocks base method.
func (m *MockModelInterface) GetCounter(ctx context.Context) (*querier.Counter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCounter", ctx)
	ret0, _ := ret[0].(*querier.Counter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCounter indicates an expected call of GetCounter.
func (mr *MockModelInterfaceMockRecorder) GetCounter(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCounter", reflect.TypeOf((*MockModelInterface)(nil).GetCounter), ctx)
}

// GetNextNotebookCellOrder mocks base method.
func (m *MockModelInterface) GetNextNotebookCellOrder(ctx context.Context, notebookUuid uuid.UUID) (int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNextNotebookCellOrder", ctx, notebookUuid)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNextNotebookCellOrder indicates an expected call of GetNextNotebookCellOrder.
func (mr *MockModelInterfaceMockRecorder) GetNextNotebookCellOrder(ctx, notebookUuid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNextNotebookCellOrder", reflect.TypeOf((*MockModelInterface)(nil).GetNextNotebookCellOrder), ctx, notebookUuid)
}

// GetNotebook mocks base method.
func (m *MockModelInterface) GetNotebook(ctx context.Context, notebookUuid uuid.UUID) (*querier.Notebook, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNotebook", ctx, notebookUuid)
	ret0, _ := ret[0].(*querier.Notebook)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNotebook indicates an expected call of GetNotebook.
func (mr *MockModelInterfaceMockRecorder) GetNotebook(ctx, notebookUuid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNotebook", reflect.TypeOf((*MockModelInterface)(nil).GetNotebook), ctx, notebookUuid)
}

// GetNotebookCell mocks base method.
func (m *MockModelInterface) GetNotebookCell(ctx context.Context, arg querier.GetNotebookCellParams) (*querier.NotebookCell, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNotebookCell", ctx, arg)
	ret0, _ := ret[0].(*querier.NotebookCell)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNotebookCell indicates an expected call of GetNotebookCell.
func (mr *MockModelInterfaceMockRecorder) GetNotebookCell(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNotebookCell", reflect.TypeOf((*MockModelInterface)(nil).GetNotebookCell), ctx, arg)
}

// InTransaction mocks base method.
func (m *MockModelInterface) InTransaction() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InTransaction")
	ret0, _ := ret[0].(bool)
	return ret0
}

// InTransaction indicates an expected call of InTransaction.
func (mr *MockModelInterfaceMockRecorder) InTransaction() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InTransaction", reflect.TypeOf((*MockModelInterface)(nil).InTransaction))
}

// IncrementCounter mocks base method.
func (m *MockModelInterface) IncrementCounter(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementCounter", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementCounter indicates an expected call of IncrementCounter.
func (mr *MockModelInterfaceMockRecorder) IncrementCounter(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementCounter", reflect.TypeOf((*MockModelInterface)(nil).IncrementCounter), ctx)
}

// ListClusters mocks base method.
func (m *MockModelInterface) ListClusters(ctx context.Context) ([]*querier.Cluster, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListClusters", ctx)
	ret0, _ := ret[0].([]*querier.Cluster)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListClusters indicates an expected call of ListClusters.
func (mr *MockModelInterfaceMockRecorder) ListClusters(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListClusters", reflect.TypeOf((*MockModelInterface)(nil).ListClusters), ctx)
}

// ListNotebookCells mocks base method.
func (m *MockModelInterface) ListNotebookCells(ctx context.Context, notebookUuid uuid.UUID) ([]*querier.NotebookCell, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListNotebookCells", ctx, notebookUuid)
	ret0, _ := ret[0].([]*querier.NotebookCell)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListNotebookCells indicates an expected call of ListNotebookCells.
func (mr *MockModelInterfaceMockRecorder) ListNotebookCells(ctx, notebookUuid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListNotebookCells", reflect.TypeOf((*MockModelInterface)(nil).ListNotebookCells), ctx, notebookUuid)
}

// ListNotebooks mocks base method.
func (m *MockModelInterface) ListNotebooks(ctx context.Context) ([]*querier.Notebook, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListNotebooks", ctx)
	ret0, _ := ret[0].([]*querier.Notebook)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListNotebooks indicates an expected call of ListNotebooks.
func (mr *MockModelInterfaceMockRecorder) ListNotebooks(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListNotebooks", reflect.TypeOf((*MockModelInterface)(nil).ListNotebooks), ctx)
}

// RunTransaction mocks base method.
func (m *MockModelInterface) RunTransaction(ctx context.Context, f func(ModelInterface) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunTransaction", ctx, f)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunTransaction indicates an expected call of RunTransaction.
func (mr *MockModelInterfaceMockRecorder) RunTransaction(ctx, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunTransaction", reflect.TypeOf((*MockModelInterface)(nil).RunTransaction), ctx, f)
}

// RunTransactionWithTx mocks base method.
func (m *MockModelInterface) RunTransactionWithTx(ctx context.Context, f func(pgx.Tx, ModelInterface) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunTransactionWithTx", ctx, f)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunTransactionWithTx indicates an expected call of RunTransactionWithTx.
func (mr *MockModelInterfaceMockRecorder) RunTransactionWithTx(ctx, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunTransactionWithTx", reflect.TypeOf((*MockModelInterface)(nil).RunTransactionWithTx), ctx, f)
}

// SpawnWithTx mocks base method.
func (m *MockModelInterface) SpawnWithTx(tx pgx.Tx) ModelInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SpawnWithTx", tx)
	ret0, _ := ret[0].(ModelInterface)
	return ret0
}

// SpawnWithTx indicates an expected call of SpawnWithTx.
func (mr *MockModelInterfaceMockRecorder) SpawnWithTx(tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SpawnWithTx", reflect.TypeOf((*MockModelInterface)(nil).SpawnWithTx), tx)
}

// UpdateCluster mocks base method.
func (m *MockModelInterface) UpdateCluster(ctx context.Context, arg querier.UpdateClusterParams) (*querier.Cluster, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCluster", ctx, arg)
	ret0, _ := ret[0].(*querier.Cluster)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCluster indicates an expected call of UpdateCluster.
func (mr *MockModelInterfaceMockRecorder) UpdateCluster(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCluster", reflect.TypeOf((*MockModelInterface)(nil).UpdateCluster), ctx, arg)
}

// UpdateNotebookCell mocks base method.
func (m *MockModelInterface) UpdateNotebookCell(ctx context.Context, arg querier.UpdateNotebookCellParams) (*querier.NotebookCell, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateNotebookCell", ctx, arg)
	ret0, _ := ret[0].(*querier.NotebookCell)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateNotebookCell indicates an expected call of UpdateNotebookCell.
func (mr *MockModelInterfaceMockRecorder) UpdateNotebookCell(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNotebookCell", reflect.TypeOf((*MockModelInterface)(nil).UpdateNotebookCell), ctx, arg)
}

// UpdateNotebookCellOrder mocks base method.
func (m *MockModelInterface) UpdateNotebookCellOrder(ctx context.Context, arg querier.UpdateNotebookCellOrderParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateNotebookCellOrder", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateNotebookCellOrder indicates an expected call of UpdateNotebookCellOrder.
func (mr *MockModelInterfaceMockRecorder) UpdateNotebookCellOrder(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNotebookCellOrder", reflect.TypeOf((*MockModelInterface)(nil).UpdateNotebookCellOrder), ctx, arg)
}

// UpdateNotebookTimestamp mocks base method.
func (m *MockModelInterface) UpdateNotebookTimestamp(ctx context.Context, notebookUuid uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateNotebookTimestamp", ctx, notebookUuid)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateNotebookTimestamp indicates an expected call of UpdateNotebookTimestamp.
func (mr *MockModelInterfaceMockRecorder) UpdateNotebookTimestamp(ctx, notebookUuid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNotebookTimestamp", reflect.TypeOf((*MockModelInterface)(nil).UpdateNotebookTimestamp), ctx, notebookUuid)
}
