// Code generated by github.com/cloudcarver/anclax DO NOT EDIT.
package counter

import "github.com/cloudcarver/waitkit/pkg/zgen/schemas/common"

type Counter struct {
	Count common.Amount `json:"count" yaml:"count"`
}

type IncrementCounterParams struct {
	Amount common.Amount `json:"amount" yaml:"amount"`
}
